"""Summarize retained actual outputs without rewriting any negative attempt."""
import collections, datetime, hashlib, json, pathlib, subprocess, yaml
root=pathlib.Path(__file__).resolve().parents[2]
out=root/'tests/W04_CAMPAIGN_BROWSER/evidence'
assert not (out/'execution-index.json').exists()
sha='31a18318f91dde34a9c75eaaac65ae1d434b7bc3'
phases=[]
for f in sorted(out.glob('*.json')):
    j=json.loads(f.read_text())
    if not isinstance(j,dict) or 'metrics' not in j: continue
    phase=j['phase']
    script = ('final-audit' if phase=='inspect' else 'bounded-followup' if phase.startswith('bounded-followup') else 'adapter-retry-repro' if phase.startswith('adapter-retry') else 'public-states' if phase.startswith('public-states') else 'menu-repro' if phase.startswith('menu-repro') else phase.rsplit('-',1)[0])
    cmd=f'node tests/W04_CAMPAIGN_BROWSER/{script}.mjs {phase}'
    if phase=='transaction-3':cmd+=' 1440'
    if phase=='inspect':cmd='W04_PHASE=final-audit-1 node tests/W04_CAMPAIGN_BROWSER/final-audit.mjs'
    phases.append({'phase':phase,'artifact':str(f.relative_to(root)),'command':cmd,'started':j['started'],'finished':j.get('finished'),'elapsed_seconds':j.get('elapsed_seconds'),'raw_check_status_counts':dict(collections.Counter(c.get('status') for c in j['checks'])),'pageerrors':sum(len(m['pageerrors']) for m in j['metrics']),'external_connections':sum(len(m['external_connections']) for m in j['metrics']),'blocked_external_attempts':sum(len(m['external_attempts']) for m in j['metrics']),'browser_contexts':len(j['metrics'])})
latest=json.loads((out/'bounded-followup-1.json').read_text())
tokens=[c for c in latest['cleanup'] if c['type']=='exact-own-token']
metrics={'contexts':sum(p['browser_contexts'] for p in phases),'pageerrors':sum(p['pageerrors'] for p in phases),'external_http_connections':sum(p['external_connections'] for p in phases),'blocked_external_attempts':sum(p['blocked_external_attempts'] for p in phases),'own_unique_tokens':len({c['hash'] for c in tokens}),'own_tokens_all_final401':all(c['requery']==401 and c['status']=='PASS' for c in tokens),'supplied_tokens_preserved':sum(c['type']=='supplied-handoff-preserved' and c['http']==200 for c in latest['cleanup'])}
index={'tested_sha':sha,'tested_tree':'c0984e682a77153753edcde318a6d44b6973b1c0','generated_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'actual_browser':'Chromium156.0.8078.4, Playwright1.60, 390x1000 touch and1440x1000 pointer','phases':phases,'metrics':metrics,'label_corrections':['inspect.json is actual final-audit.mjs: W04_PHASE env was unused; argv phase default was inspect. No output overwritten.','transaction-2 two successful inquiry checks have raw status TEST_INQUIRY because early step helper treated business status as gate status. Successful assertions/native201 are retained, interpreted as bounded PASS only; no raw rewrite.','campaign-2 syntax failure created no browser phase; see campaign-2-syntax.json.','common-campaign5-reconstructed.mjs is retrospective reconstruction, not an execution-time saved file. Other archived scripts are copied executed variants; current common plus named snapshots records later changes.','source-binding after exit1 is retained. Missing inherited during_verification keys explain false summary fields; binding-audit compares actual before/after supplements. Optional basic absent463 disclosed.'],'commands_extra':[{'command':'git fetch origin feat/g7-travel-lab-c7ae42d1','exit':0},{'command':'git checkout --detach 31a18318f91dde34a9c75eaaac65ae1d434b7bc3','exit':0},{'command':'npm ci --ignore-scripts','exit':0,'scope':'own worktree harness dependencies; no parent build'},{'command':'python3 tests/W04_CAMPAIGN_BROWSER/source-binding.py before','exit':0},{'command':'python3 tests/W04_CAMPAIGN_BROWSER/source-binding.py after','exit':1},{'command':'python3 tests/W04_CAMPAIGN_BROWSER/binding-audit.py','exit':0}],'sql':'NOT_RUN forbidden','test_schema':'NOT_RUN offlimits','ci_runs':0,'canonical_validation':'NOT_RUN absent','product_changes':0,'official_children':0}
(out/'execution-index.json').write_text(json.dumps(index,indent=2)+'\n')
source=root/'tests/scenarios/travel-lab.yaml';contract=yaml.safe_load(source.read_text())
incremental={'TR-CATALOG-001':'PASS bounded nature/wellness campaign CTA/theme/search/card/detail; culture/city/full bounds NOT_RUN','TR-CART-001':'PASS native add quantity2/update3/down2 consumed cart; nontravel/order-table queries NOT_RUN','TR-INQUIRY-001':'PASS native201 server13700x2 snapshot/API allocation/events; SQL/external adapter internals NOT_RUN','TR-IDEMPOTENCY-001':'PASS actual upstream201 aborted delivery/reload native200 sameID/key/items/events/amount/API reserved; both widths','TR-IDEMPOTENCY-002':'NOT_RUN changed payload conflict','TR-CONCURRENCY-001':'NOT_RUN no SQL/separate connections permitted','TR-ADMIN-001':'PASS actual390 accepted and1440 declined via nativeUI/relogin; desktop stabilized menu pointer PASS after earlier failures','TR-RELEASE-001':'PASS accepted cancellation200 and declined terminal409/API reserved0; commerce-stock/repeated-cancel matrix NOT_RUN','TR-ACCESS-001':'PASS bounded inquiry/privatequestion other-member404/native Page guest401/member403; scoped Page actor BLOCKED; attachment matrix NOT_RUN','TR-SUPPORT-001':'PASS bounded native noticeFAQ/question/answer create/edit/read3901440; no attachments created','TR-RESTART-001':'PASS relogin/requery only; preview restart NOT_RUN runtime immutable','TR-MIGRATION-001':'NOT_RUN APP/TEST install/seed/rollback forbidden','TR-UI-001':'FAIL admin campaign Retry native200 retains error3901440; customer flow/state/overflow bounded PASS','TR-REGRESSION-001':'PASS selected installed/served binding and support smoke only; builds/unit suites/full14/CI/Validation NOT_RUN'}
for c in contract['scenarios']:
    c['full_required_effect_matrix_status']='NOT_RUN'
    c['current_incremental_observation']=incremental[c['id']]
matrix={'fixed_review_sha':sha,'source_contract_sha256':hashlib.sha256(source.read_bytes()).hexdigest(),'source_contract_input_sha':contract['input_source_sha'],'note':'Historic contract input6853 is preserved as contract provenance, never the tested source. Entire 14-scenario cross-product not rerun; every original action/effect/axis retained. Incremental actual results are separate. Independent TEST permission gate not consumed as our PASS.','contract':contract}
(out/'required-matrix.json').write_text(json.dumps(matrix,indent=2)+'\n')
print(json.dumps({'phases':len(phases),'metrics':metrics}))
