<?php

declare(strict_types=1);
require __DIR__.'/environment.php';
require __DIR__.'/migration-bootstrap.php';
$root = dirname(__DIR__, 2);

try {
    if (! is_file($root.'/vendor/autoload.php')) {
        throw new RuntimeException('Install root Composer dependencies first.');
    }
    foreach (['.env', '.env.testing'] as $file) {
        if (is_file($root.'/'.$file) && ! preg_match('/^TRAVEL_LAB_ISOLATED=1$/m', file_get_contents($root.'/'.$file))) {
            throw new RuntimeException('Refusing to replace an existing non-lab '.$file);
        }
    }
    if (! is_file($root.'/.env')) {
        $contents = file_get_contents($root.'/.env.travel-lab.example');
        $dbPassword = bin2hex(random_bytes(24));
        $contents = str_replace('APP_KEY=', 'APP_KEY=base64:'.base64_encode(random_bytes(32)), $contents);
        $contents = str_replace(['DB_WRITE_PASSWORD=', 'DB_READ_PASSWORD='], ['DB_WRITE_PASSWORD='.$dbPassword, 'DB_READ_PASSWORD='.$dbPassword], $contents);
        $contents = str_replace('INSTALLER_ADMIN_PASSWORD=', 'INSTALLER_ADMIN_PASSWORD='.bin2hex(random_bytes(16)), $contents);
        file_put_contents($root.'/.env', $contents);
        chmod($root.'/.env', 0600);
    }
    // Recover older generated lab envs without replacing their local-only secrets.
    foreach (['.env', '.env.testing'] as $file) {
        foreach (['G7_ENV_PRIORITY' => 'true', 'TRAVEL_LAB_SUPPORT_PROVISIONING' => '1', 'TRAVEL_LAB_CAMPAIGN_PROVISIONING' => '0'] as $key => $value) {
            if (is_file($root.'/'.$file) && ! preg_match('/^'.preg_quote($key, '/').'=/m', file_get_contents($root.'/'.$file))) {
                file_put_contents($root.'/'.$file, file_get_contents($root.'/'.$file)."\n$key=$value\n");
            }
        }
    }
    if (! is_file($root.'/.env.testing')) {
        $contents = str_replace(['APP_ENV=local', 'req81_travel_lab'], ['APP_ENV=testing', 'req81_travel_lab_test'], file_get_contents($root.'/.env'));
        $contents = preg_replace('/^CACHE_STORE=.*$/m', 'CACHE_STORE=array', $contents);
        file_put_contents($root.'/.env.testing', $contents);
        chmod($root.'/.env.testing', 0600);
    }
    $environment = travelLabEnvironment();
    $testEnvironment = travelLabEnvironment(true);
    $password = $environment['DB_WRITE_PASSWORD'];
    if (! preg_match('/^[a-f0-9]{48}$/', $password)) {
        throw new RuntimeException('Lab DB secret must be generated by setup.');
    }
    if ($testEnvironment['DB_WRITE_PASSWORD'] !== $password || $testEnvironment['DB_READ_PASSWORD'] !== $password) {
        // If only one ignored env survived, preserve its app key and other settings,
        // but keep both schemas' credentials aligned with their single scoped account.
        $testContents = preg_replace('/^(DB_(?:READ|WRITE)_PASSWORD)=.*$/m', '$1='.$password, file_get_contents($root.'/.env.testing'));
        file_put_contents($root.'/.env.testing', $testContents);
        chmod($root.'/.env.testing', 0600);
    }
    // A recreated worktree loses ignored env files while the DB account can survive.
    // Refuse an unexpectedly privileged account before changing its authentication.
    $grantee = "CONCAT(CHAR(39),'req81_travel',CHAR(39),'@',CHAR(39),'127.0.0.1',CHAR(39))";
    $foreignGrants = travelLabAdminSql('SELECT COUNT(*) FROM ('
        ."SELECT 1 FROM information_schema.USER_PRIVILEGES WHERE GRANTEE=$grantee AND PRIVILEGE_TYPE <> 'USAGE' "
        ."UNION ALL SELECT 1 FROM information_schema.SCHEMA_PRIVILEGES WHERE GRANTEE=$grantee AND TABLE_SCHEMA NOT IN ('req81_travel_lab','req81_travel_lab_test') "
        ."UNION ALL SELECT 1 FROM information_schema.TABLE_PRIVILEGES WHERE GRANTEE=$grantee AND TABLE_SCHEMA NOT IN ('req81_travel_lab','req81_travel_lab_test') "
        ."UNION ALL SELECT 1 FROM information_schema.COLUMN_PRIVILEGES WHERE GRANTEE=$grantee AND TABLE_SCHEMA NOT IN ('req81_travel_lab','req81_travel_lab_test')) AS unsafe_grants;\n");
    if ((int) trim($foreignGrants) !== 0) {
        throw new RuntimeException('Refusing a lab DB account with privileges outside the two lab schemas.');
    }
    $sql = "CREATE DATABASE IF NOT EXISTS req81_travel_lab CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;\n"
        ."CREATE DATABASE IF NOT EXISTS req81_travel_lab_test CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;\n"
        ."CREATE USER IF NOT EXISTS 'req81_travel'@'127.0.0.1' IDENTIFIED BY '$password';\n"
        ."ALTER USER 'req81_travel'@'127.0.0.1' IDENTIFIED BY '$password';\n"
        ."GRANT ALL PRIVILEGES ON req81_travel_lab.* TO 'req81_travel'@'127.0.0.1';\n"
        ."GRANT ALL PRIVILEGES ON req81_travel_lab_test.* TO 'req81_travel'@'127.0.0.1';\n";
    travelLabAdminSql($sql);
    foreach (['storage/framework/cache/data', 'storage/framework/sessions', 'storage/framework/views', 'storage/logs'] as $directory) {
        if (! is_dir($root.'/'.$directory)) {
            mkdir($root.'/'.$directory, 0770, true);
        }
    }
    $pdo = new PDO('mysql:host=127.0.0.1;port=3306;dbname=req81_travel_lab', 'req81_travel', $password, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);
    echo 'PASS: isolated development/test DBs provisioned; secrets remain in ignored environment files.'.PHP_EOL;
    foreach ([['migrate', '--no-interaction'], ['settings:install', '--no-interaction']] as $command) {
        $migrationEnvironment = $command[0] === 'migrate'
            ? travelLabInitialMigrationEnvironment($pdo, $environment, $root) : $environment;
        if (travelLabLifecycleProcess([PHP_BINARY, 'artisan', ...$command], $migrationEnvironment) !== 0) {
            throw new RuntimeException('Installation step failed: '.$command[0]);
        }
    }
    // Core AdminUserSeeder deletes all users: only run it on a genuinely empty lab DB.
    if ((int) $pdo->query('SELECT COUNT(*) FROM g7_users')->fetchColumn() === 0) {
        if (travelLabLifecycleProcess([PHP_BINARY, 'artisan', 'db:seed', '--class=DatabaseSeeder', '--no-interaction'], $environment) !== 0) {
            throw new RuntimeException('Core seed failed.');
        }
    } else {
        echo 'Core seed skipped: existing lab users preserved.'.PHP_EOL;
    }
    if (travelLabLifecycleProcess([PHP_BINARY, 'scripts/travel-lab/live-admin.php'], $environment) !== 0) {
        throw new RuntimeException('Synthetic administrator credential recovery failed.');
    }
    $contents = file_get_contents($root.'/.env');
    file_put_contents($root.'/.env', str_replace('INSTALLER_COMPLETED=false', 'INSTALLER_COMPLETED=true', $contents));
    echo 'PASS: core lab initialized. Run extensions.php after bundled travel artifacts are present.'.PHP_EOL;
} catch (Throwable $error) {
    fwrite(STDERR, 'BLOCKED: '.$error->getMessage().PHP_EOL);
    exit(1);
}
