<?php

declare(strict_types=1);
require __DIR__.'/environment.php';
$root = dirname(__DIR__, 2);

try {
    if (! is_file($root.'/vendor/autoload.php')) {
        throw new RuntimeException('Install root Composer dependencies first.');
    }
    foreach (['.env', '.env.testing'] as $file) {
        if (is_file($root.'/'.$file) && ! preg_match('/^TRAVEL_LAB_ISOLATED=1$/m', file_get_contents($root.'/'.$file))) {
            throw new RuntimeException('Refusing to replace an existing non-lab '.$file);
        }
    }
    if (! is_file($root.'/.env')) {
        $contents = file_get_contents($root.'/.env.travel-lab.example');
        $dbPassword = bin2hex(random_bytes(24));
        $contents = str_replace('APP_KEY=', 'APP_KEY=base64:'.base64_encode(random_bytes(32)), $contents);
        $contents = str_replace(['DB_WRITE_PASSWORD=', 'DB_READ_PASSWORD='], ['DB_WRITE_PASSWORD='.$dbPassword, 'DB_READ_PASSWORD='.$dbPassword], $contents);
        $contents = str_replace('INSTALLER_ADMIN_PASSWORD=', 'INSTALLER_ADMIN_PASSWORD='.bin2hex(random_bytes(16)), $contents);
        file_put_contents($root.'/.env', $contents);
        chmod($root.'/.env', 0600);
    }
    // Recover older generated lab envs without replacing their local-only secrets.
    foreach (['.env', '.env.testing'] as $file) {
        if (is_file($root.'/'.$file) && ! preg_match('/^G7_ENV_PRIORITY=true$/m', file_get_contents($root.'/'.$file))) {
            file_put_contents($root.'/'.$file, file_get_contents($root.'/'.$file)."\nG7_ENV_PRIORITY=true\n");
        }
    }
    if (! is_file($root.'/.env.testing')) {
        $contents = str_replace(['APP_ENV=local', 'req81_travel_lab'], ['APP_ENV=testing', 'req81_travel_lab_test'], file_get_contents($root.'/.env'));
        file_put_contents($root.'/.env.testing', $contents);
        chmod($root.'/.env.testing', 0600);
    }
    $environment = travelLabEnvironment();
    travelLabEnvironment(true);
    $password = $environment['DB_WRITE_PASSWORD'];
    if (! preg_match('/^[a-f0-9]{48}$/', $password)) {
        throw new RuntimeException('Lab DB secret must be generated by setup.');
    }
    $sql = "CREATE DATABASE IF NOT EXISTS req81_travel_lab CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;\n"
        ."CREATE DATABASE IF NOT EXISTS req81_travel_lab_test CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;\n"
        ."CREATE USER IF NOT EXISTS 'req81_travel'@'127.0.0.1' IDENTIFIED BY '$password';\n"
        ."GRANT ALL PRIVILEGES ON req81_travel_lab.* TO 'req81_travel'@'127.0.0.1';\n"
        ."GRANT ALL PRIVILEGES ON req81_travel_lab_test.* TO 'req81_travel'@'127.0.0.1';\n";
    $process = proc_open(['sudo', '-n', 'mysql', '--protocol=socket', '-uroot'], [0 => ['pipe', 'r'], 1 => STDOUT, 2 => STDERR], $pipes);
    if (! is_resource($process)) {
        throw new RuntimeException('Local administrative socket unavailable.');
    }
    fwrite($pipes[0], $sql);
    fclose($pipes[0]);
    if (proc_close($process) !== 0) {
        throw new RuntimeException('Local DB provisioning failed; no external DB fallback is permitted.');
    }
    foreach (['storage/framework/cache/data', 'storage/framework/sessions', 'storage/framework/views', 'storage/logs'] as $directory) {
        if (! is_dir($root.'/'.$directory)) {
            mkdir($root.'/'.$directory, 0770, true);
        }
    }
    $pdo = new PDO('mysql:host=127.0.0.1;port=3306;dbname=req81_travel_lab', 'req81_travel', $password, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);
    echo 'PASS: isolated development/test DBs provisioned; secrets remain in ignored environment files.'.PHP_EOL;
    foreach ([['migrate', '--no-interaction'], ['settings:install', '--no-interaction']] as $command) {
        if (travelLabProcess([PHP_BINARY, 'artisan', ...$command], $environment) !== 0) {
            throw new RuntimeException('Installation step failed: '.$command[0]);
        }
    }
    // Core AdminUserSeeder deletes all users: only run it on a genuinely empty lab DB.
    if ((int) $pdo->query('SELECT COUNT(*) FROM g7_users')->fetchColumn() === 0) {
        if (travelLabProcess([PHP_BINARY, 'artisan', 'db:seed', '--class=DatabaseSeeder', '--no-interaction'], $environment) !== 0) {
            throw new RuntimeException('Core seed failed.');
        }
    } else {
        echo 'Core seed skipped: existing lab users preserved.'.PHP_EOL;
    }
    $contents = file_get_contents($root.'/.env');
    file_put_contents($root.'/.env', str_replace('INSTALLER_COMPLETED=false', 'INSTALLER_COMPLETED=true', $contents));
    echo 'PASS: core lab initialized. Run extensions.php after bundled travel artifacts are present.'.PHP_EOL;
} catch (Throwable $error) {
    fwrite(STDERR, 'BLOCKED: '.$error->getMessage().PHP_EOL);
    exit(1);
}
