<?php
require __DIR__.'/runtime-bootstrap.php';
$app=w04App();$records=[];
foreach($app['router']->getRoutes() as $r){if(str_starts_with($r->uri(),'api/modules/raonslab-travel_lab/')){$records[]=['uri'=>$r->uri(),'methods'=>$r->methods(),'name'=>$r->getName(),'middleware'=>$app['router']->gatherRouteMiddleware($r)];}}
$classes=[Modules\Raonslab\TravelLab\Module::class,Modules\Raonslab\TravelLab\Services\InquiryService::class,Modules\Raonslab\TravelLab\Services\TravelCartService::class,Modules\Raonslab\TravelLab\Services\CampaignService::class,Modules\Raonslab\TravelLab\Services\TravelCampaignProvisioner::class,Modules\Sirsoft\Ecommerce\Services\ProductService::class,Modules\Sirsoft\Board\Services\PostService::class,Modules\Sirsoft\Page\Services\PageService::class];$origins=[];
foreach($classes as $c){$f=(new ReflectionClass($c))->getFileName();$r=str_replace(w04fRoot().'/','',$f);if(!str_starts_with($r,'modules/')||str_contains($r,'/_bundled/')){throw new RuntimeException('Installed origin rejected.');}$b=str_replace('modules/','modules/_bundled/',$r);$ok=hash_file('sha256',$f)===hash_file('sha256',w04fRoot().'/'.$b);if(!$ok){throw new RuntimeException('Installed source bytes mismatch.');}$origins[$c]=['path'=>$r,'sha256'=>hash_file('sha256',$f),'bundled_equal'=>$ok];}
$cache=$app['cache']->store()->getStore();$permissions=[];
foreach(['admin','manager','user'] as $id){$role=App\Models\Role::where('identifier',$id)->firstOrFail();$permissions[$id]=$role->permissions()->where('identifier','like','raonslab-travel_lab.%')->pluck('identifier')->sort()->values()->all();}
$cacheFile=w04fRoot().'/bootstrap/cache/routes-v7.php';
$r=['phase'=>$argv[1]??'before','utc'=>gmdate('c'),'source_sha'=>'5783e6ba124061bdfae639cdaf9b1c14a83cdf03','app_env'=>$app->environment(),'routes_cached'=>$app->routesAreCached(),'route_cache_sha256'=>is_file($cacheFile)?hash_file('sha256',$cacheFile):null,'routes'=>$records,'api_count'=>count($records),'origins'=>$origins,'permissions'=>$permissions,'adapters'=>[],'cache'=>['class'=>get_class($cache),'counter_db'=>$cache->getConnection()->getDatabaseName(),'lock_db'=>$cache->getLockConnection()->getDatabaseName(),'counter_table'=>config('cache.stores.database.table'),'lock_table'=>config('cache.stores.database.lock_table'),'prefix'=>config('cache.prefix')]];
foreach(['mail.default','queue.default','filesystems.default','scout.driver','cache.default','session.driver'] as $k){$r['adapters'][$k]=config($k);}
w04Save(w04fEvidence('runtime').'/'.($argv[1]??'before').'.json',$r);Illuminate\Support\Facades\DB::purge();echo 'PASS native installed origins/routes/cache/adapters'.PHP_EOL;
