import fs from 'node:fs';import crypto from 'node:crypto';import path from 'node:path';import {execFileSync} from 'node:child_process';import {chromium,expect as originalExpect} from '@playwright/test';
export const expect=originalExpect.configure({timeout:15000});export const SHA='fa5523175ac494cfbd13bbf89bf06b3ec91835a6',out='docs/symphony/evidence/W04_NATIVE_ADMIN',travel='/api/modules/raonslab-travel_lab';
const file='/home/ubuntu/.agentopt-v2/workspaces/req_81ac33cac94046b9a2249cd14c0d00ba/storage/framework/testing/travel-live-review-fb40eddf4a39/access.json';
if(fs.lstatSync(file).isSymbolicLink()||(fs.statSync(file).mode&0o077)||(fs.statSync(path.dirname(file)).mode&0o077))throw Error('Private scoped access required');
export const a=JSON.parse(fs.readFileSync(file));if(a.source_sha!==SHA||a.db!=='req81_travel_lab'||(!Number.isFinite(Date.parse(a.expires_at))||Date.parse(a.expires_at)<=Date.now())||a.base_url!=='http://127.0.0.1:18871')throw Error('Access binding/expiry mismatch');
export const actualHead=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim();
execFileSync('git',['merge-base','--is-ancestor',SHA,actualHead]);
const changes=execFileSync('git',['diff','--name-only',SHA],{encoding:'utf8'}).trim().split('\n').filter(Boolean);if(changes.some(p=>!p.startsWith('tests/W04_NATIVE_ADMIN/')&&!p.startsWith(out+'/')&&p!=='docs/symphony/W04_NATIVE_ADMIN_BROWSER_FINAL.md'))throw Error('Product revision mismatch');
fs.mkdirSync('tests/W04_NATIVE_ADMIN/.private',{recursive:true,mode:0o700});
if(fs.statSync('tests/W04_NATIVE_ADMIN/.private').mode&0o077)throw Error('Own private token ledger directory permissions required');
const issued=[];
export const base=a.base_url,run='W04N'+Date.now(),results=[],metrics=[],owned={inquiries:[],carts:[],products:[],posts:[],policies:[],categories:[]};fs.mkdirSync(out,{recursive:true});
// 실제 연락처를 코드에 고정하지 않고 테스트 프로세스 안에서만 합성한다.
export const syntheticPhone=(edited=false)=>[String(0).repeat(3),String(0).repeat(4),String(0).repeat(3)+(edited?'1':'0')].join('-');
export const hash=x=>crypto.createHash('sha256').update(typeof x==='string'||Buffer.isBuffer(x)?x:JSON.stringify(x)).digest('hex');
export function scrub(s){s=String(s).replace(/\u001b\[[0-9;]*m/g,'');for(const t of issued)s=s.replaceAll(t,'[private token]');for(const r of ['member','other_member','admin'])for(const v of Object.values(a[r]))if(typeof v==='string')s=s.replaceAll(v,'[private]');return s.replace(/W04N.*?contact[^\"\n]*/g,'[synthetic contact]').replace(/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}/gi,'[private uuid]').replace(/Bearer\s+\S+/gi,'Bearer [private]').replace(/[\w.+-]+@[\w.-]+\.[\w-]+/g,'[private email]').replace(/000-0000-000[01]/g,'[synthetic contact]');}
export function flush(name){const ledgerFile=out+'/fixtures.json';const prev=fs.existsSync(ledgerFile)?JSON.parse(fs.readFileSync(ledgerFile)):{};for(const k of Object.keys(owned)){prev[k]=[...(prev[k]??[]),...owned[k]].filter((x,i,arr)=>arr.findIndex(y=>y.id===x.id&&y.role===x.role&&y.slug===x.slug)===i);}fs.writeFileSync(ledgerFile,JSON.stringify(prev,null,2)+'\n');fs.writeFileSync(out+'/'+name+'.json',scrub(JSON.stringify({tested_sha:SHA,actual_head:actualHead,browserVersion:browser.version(),run,elapsed_seconds:(Date.now()-Number(run.slice(4)))/1000,results,metrics,owned},null,2))+'\n');}
export async function step(width,name,fn,file='journey'){try{const detail=await fn();results.push({width,name,status:['PASS','FAIL','NOT_RUN','BLOCKED'].includes(detail?.status)?detail.status:'PASS',detail});console.log(width,name,results.at(-1).status);return results.at(-1).status==='PASS';}catch(e){results.push({width,name,status:'FAIL',error:scrub(e.message).slice(0,1600)});console.log(width,name,'FAIL',scrub(e.message).split('\n')[0]);return false;}finally{flush(file);}}
export const browser=await chromium.launch({executablePath:'/home/ubuntu/.cache/ms-playwright/chromium-1248/chrome-linux64/chrome'});
let nativeClick;export async function context(width,role='guest'){const c=await browser.newContext({locale:'ko-KR',viewport:{width,height:1000},hasTouch:width===390,isMobile:width===390}),p=await c.newPage();p.setDefaultTimeout(20000);p.setDefaultNavigationTimeout(45000);if(!nativeClick){const proto=Object.getPrototypeOf(p.locator('html'));nativeClick=proto.click;proto.click=function(options){return this.page().viewportSize()?.width===390?this.tap(options):nativeClick.call(this,options);};}const originalWait=p.waitForResponse.bind(p);p.waitForResponse=(...args)=>{const promise=originalWait(...args);promise.catch(()=>{});return promise;};const m={width,role,pageErrors:[],consoleErrors:[],requests:[],responses:[],httpErrors:[],overflow:[],assets:[]};metrics.push(m);p.on('pageerror',e=>m.pageErrors.push(scrub(e.message)));p.on('console',e=>{if(e.type()==='error')m.consoleErrors.push(scrub(e.text()).slice(0,1600));});p.on('request',r=>{const pathname=new URL(r.url()).pathname;if(pathname.startsWith('/api/'))m.requests.push({path:pathname,method:r.method(),nativeBearer:!!r.headers().authorization?.startsWith('Bearer ')});});p.on('response',r=>{if(new URL(r.url()).pathname.startsWith('/api/'))m.responses.push({path:new URL(r.url()).pathname,method:r.request().method(),status:r.status()});if(/\.(js|css|woff2?)(?:$|\?)/.test(r.url()))r.body().then(b=>{const item={path:new URL(r.url()).pathname,status:r.status(),sha256:hash(b),bytes:b.length};if(!m.assets.some(x=>x.path===item.path&&x.sha256===item.sha256))m.assets.push(item);}).catch(()=>{});if(r.status()>=400)m.httpErrors.push({path:new URL(r.url()).pathname,status:r.status()});});return {p,c,m};}
export async function login(p,role){await p.goto(base+'/login');await p.locator('#travel-login-email').fill(a[role].email);await p.locator('#travel-login-password').fill(a[role].password);const wait=p.waitForResponse(r=>new URL(r.url()).pathname==='/api/auth/login'&&r.request().method()==='POST');if(p.viewportSize().width===390)await p.locator('form button[type=submit]').tap();else await p.locator('form button[type=submit]').click();const response=await wait;expect(response.status()).toBe(200);const body=await response.json();const token=body.data?.token||body.data?.access_token;if(typeof token!=='string'||!token)throw Error('Native login returned no auditable token');if(token){issued.push(token);fs.appendFileSync(out+'/token-issuance.jsonl',JSON.stringify({role,tokenSHA256:hash(token),nativeLogin:200})+'\n');fs.writeFileSync('tests/W04_NATIVE_ADMIN/.private/token-'+hash(token)+'.json',JSON.stringify({token,role}),{mode:0o600});const tf='tests/W04_NATIVE_ADMIN/.private/issued.json';const prev=fs.existsSync(tf)?JSON.parse(fs.readFileSync(tf)):[];prev.push({token,role});fs.writeFileSync(tf,JSON.stringify(prev),{mode:0o600});}await expect(p).not.toHaveURL(/\/login/);}
export async function shot(p,m,name){
 if(!name.includes('loading'))await p.waitForLoadState('networkidle');let previous='';for(let n=0;n<24;n++){await p.waitForTimeout(150);const current=await p.locator('body').innerText();if(current===previous&&n>=6)break;previous=current;}
 const privateValues=[];for(const role of ['member','other_member','admin'])for(const [k,v] of Object.entries(a[role]))if(typeof v==='string'&&v.length>3)privateValues.push(v);privateValues.push(syntheticPhone(),syntheticPhone(true));privateValues.push(...issued);
 await p.evaluate(values=>{window.__shotObserver?.disconnect();window.__maskStyles=[...document.querySelectorAll('input,textarea,[contenteditable=true]')].map(e=>[e,e.style.cssText]);const mask=()=>{for(const e of document.querySelectorAll('input,textarea,[contenteditable=true]'))e.style.setProperty('visibility','hidden','important');const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let node;while(node=walker.nextNode()){if(node.parentElement?.closest('script,style'))continue;let t=node.textContent;for(const value of values)t=t.split(value).join('[MASKED]');t=t.replace(/[\w.+-]+@[\w.-]+\.[\w-]+/g,'[MASKED EMAIL]').replace(/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}/gi,'[MASKED UUID]').replace(/W04N\d+ contact[^\n]*/g,'[MASKED CONTACT]').replace(/\b\d+\|[A-Za-z0-9]{30,}\b/g,'[MASKED TOKEN]');if(t!==node.textContent)node.textContent=t;}};mask();window.__shotObserver=new MutationObserver(()=>{window.__shotObserver.disconnect();mask();window.__shotObserver.observe(document.body,{subtree:true,childList:true,characterData:true});});window.__shotObserver.observe(document.body,{subtree:true,childList:true,characterData:true});},privateValues);
 await p.waitForTimeout(450);const file=out+'/'+name+'-'+m.width+'.png';await p.screenshot({path:file,fullPage:true});
 const ocr=execFileSync('tesseract',[file,'stdout'],{encoding:'utf8',stdio:['ignore','pipe','ignore'],env:{...process.env,OMP_THREAD_LIMIT:'1'},timeout:60000});const hits=privateValues.filter(v=>v.length>=5&&ocr.includes(v));if(hits.length||/[\w.+-]+@[\w.-]+\.[\w-]+|\b\d+\|[A-Za-z0-9]{30,}/.test(ocr)){fs.unlinkSync(file);throw Error('Screenshot privacy OCR rejected; PNG removed, values withheld');}
 results.push({width:m.width,name:'privacy OCR '+name,status:'PASS',knownValueHits:0,tokenPatternHits:0});await p.evaluate(()=>{window.__shotObserver.disconnect();for(const [e,s] of window.__maskStyles)e.style.cssText=s;});
 const o=await p.evaluate(()=>({viewport:innerWidth,document:document.documentElement.scrollWidth}));m.overflow.push({name,...o});if(o.document>m.width)results.push({width:m.width,name:'horizontal overflow '+name,status:'FAIL',detail:o});
}
export async function api(p,path,method='GET',data,role='member'){const r=await p.request.fetch(base+path,{method,headers:{Accept:'application/json',Authorization:'Bearer '+a[role].bearer_token},...(data!==undefined?{data}:{})});return {status:r.status(),body:await r.json()};}
export async function cleanup(p){for(const f of owned.inquiries){const q=await api(p,travel+'/inquiries/'+f.id,'GET',undefined,f.role);if(!['CANCELLED','DECLINED'].includes(q.body.data?.status))await api(p,travel+'/inquiries/'+f.id+'/cancel','POST',{},f.role);const r=await api(p,travel+'/inquiries/'+f.id,'GET',undefined,f.role);results.push({name:'cleanup own inquiry',status:['CANCELLED','DECLINED'].includes(r.body.data?.status)?'PASS':'FAIL',id:f.id,terminalState:r.body.data?.status});}for(const f of owned.carts){const r=await api(p,travel+'/cart','GET',undefined,f.role);if(r.body.data?.items.some(x=>x.id===f.id))await api(p,travel+'/cart/'+f.id,'DELETE',undefined,f.role);}for(const f of owned.posts){const r=await api(p,'/api/modules/sirsoft-board/admin/board/'+f.slug+'/posts/'+f.id,'DELETE',undefined,'admin');const q=await api(p,'/api/modules/sirsoft-board/admin/board/'+f.slug+'/posts/'+f.id,'GET',undefined,'admin');results.push({name:'cleanup own support post',id:f.id,status:r.status===200&&!!q.body.data?.deleted_at?'PASS':'FAIL',http:r.status,requery:q.status});}}

export async function finishTokens(p){const af=out+'/token-audit.json';const audit=fs.existsSync(af)?JSON.parse(fs.readFileSync(af)):[];for(const token of issued){const r=await p.request.post(base+'/api/auth/logout',{headers:{Accept:'application/json',Authorization:'Bearer '+token},data:{}});const q=await p.request.get(base+'/api/auth/user',{headers:{Accept:'application/json',Authorization:'Bearer '+token}});results.push({name:'delete exact own issued token native logout then401',status:[200,401].includes(r.status())&&q.status()===401?'PASS':'FAIL',http:r.status(),requery:q.status(),tokenSHA256:hash(token)});audit.push(results.at(-1));fs.writeFileSync(af,JSON.stringify(audit,null,2)+'\n');}flush('issued-token-cleanup');}
export async function logout(p,width){if(width===390)await p.getByTestId('menu-toggle').click();const w=p.waitForResponse(r=>r.url().endsWith('/api/auth/logout'));await p.getByRole('button',{name:'로그아웃',exact:true}).click();expect((await w).status()).toBe(200);await expect(p).toHaveURL(/\/login/);}

export const pointer=async locator=>locator.page().viewportSize().width===390?locator.tap():locator.click();

// Budget per authenticated user is10 writes/minute. Record actual attempts, wait own window;
// never alter throttle/cache/grants. Minimum spacing for new fixture/recovery batches.
export async function inquiryBudgetWait(){const file=out+'/inquiry-budget.json';let times=fs.existsSync(file)?JSON.parse(fs.readFileSync(file)):[];times=times.filter(t=>Date.now()-t<65000);if(times.length>=8){const ms=Math.max(0,65000-(Date.now()-times[0]));results.push({name:'request-specific own inquiry write-window wait',status:'PASS',milliseconds:ms,reason:'fixed authenticated10/min budget; reserved2 attempts for normal native retry'});await new Promise(resolve=>setTimeout(resolve,ms));times=times.filter(t=>Date.now()-t<65000);}times.push(Date.now());fs.writeFileSync(file,JSON.stringify(times));}
