import {a,base,out,travel,run,context,login,browser,expect,shot,api,step,owned,cleanup,flush,results,scrub,finishTokens} from './common.mjs';import fs from 'node:fs';
const commerce='/api/modules/sirsoft-ecommerce/admin';
for(const width of [390,1440]){
 const {p,c,m}=await context(width,'admin');await login(p,'admin');let policy,product,category,categoryTitle=run+' 합성분류 '+width;
 await step(width,'native UI NEW active root category201 unique slug',async()=>{
 const prior=JSON.parse(fs.readFileSync(out+'/fixtures.json')).categories.find(x=>x.width===width);if(prior){category=prior.id;const q=await api(p,commerce+'/categories/'+category,'GET',undefined,'admin');categoryTitle=q.body.data.name.ko;owned.categories.push(prior);return {id:category,reuseOwnCreatedUi201:true};}await p.goto(base+'/admin/ecommerce/categories');await p.waitForLoadState('networkidle');await expect(p.locator('#add_category_button')).toBeEnabled();await p.locator('#add_category_button').click();await expect(p.locator('input[name="name[ko]"]:visible')).toBeVisible();await p.locator('input[name="name[ko]"]:visible').fill(categoryTitle);await p.locator('input[name=slug]:visible').fill(run.toLowerCase()+'-'+width);const w=p.waitForResponse(r=>r.url().endsWith(commerce+'/categories')&&r.request().method()==='POST');await p.locator('button[form=category_form]').click();const r=await w;const d=await r.json();expect(r.status()).toBe(201);category=d.data.id;owned.categories.push({id:category,width,slug:run.toLowerCase()+'-'+width});flush('admin');const q=await api(p,commerce+'/categories/'+category,'GET',undefined,'admin');expect(q.body.data.is_active).toBe(true);expect(q.body.data.parent_id).toBeNull();await shot(p,m,'new-category-created');return {id:category,http:201,is_active:true,root:true};},'admin');
 await step(width,'native UI NEW nondefault free pickup KR shippingpolicy201',async()=>{
 globalThis.policyTitle=run+' 무료정책 '+width;await p.goto(base+'/admin/ecommerce/shipping-policies/create');await expect(p.locator('input[name="name[ko]"]:visible')).toBeVisible();await p.locator('input[name="name[ko]"]').fill(globalThis.policyTitle);await p.locator('#add_country_area button').first().click();await p.getByRole('option').filter({hasText:'KR'}).click();await p.locator('#add_country_area').getByRole('button',{name:/국가 추가/}).click();await expect(p.locator('#field_country_shipping_method')).toBeVisible();await p.locator('#field_country_shipping_method button').click();await p.getByRole('option',{name:/매장수령|방문수령|직접 수령|직접수령/}).click();await p.locator('#field_charge_policy button').click();await p.getByRole('option',{name:/^무료배송$/}).click();await expect(p.getByRole('switch',{name:'기본 배송정책',exact:true})).toHaveAttribute('aria-checked','false');const w=p.waitForResponse(r=>r.url().endsWith(commerce+'/shipping-policies')&&r.request().method()==='POST');await p.getByRole('button',{name:'저장',exact:true}).click();const r=await w;const d=await r.json();if(r.status()!==201)console.log(scrub(JSON.stringify({status:r.status(),message:d.message,errors:d.errors})));expect(r.status()).toBe(201);policy=d.data.id;owned.policies.push({id:policy,width});flush('admin');const q=await api(p,commerce+'/shipping-policies/'+policy,'GET',undefined,'admin');expect(q.body.data.is_default).toBe(false);expect(q.body.data.country_settings.some(x=>x.country_code==='KR'&&x.charge_policy==='free'&&x.shipping_method==='pickup'&&Number(x.base_fee)===0)).toBe(true);await shot(p,m,'new-policy-created');return {id:policy,http:201,is_default:false,method:'pickup',country:'KR',fee:0};},'admin');
 if(!policy){results.push({width,name:'critical admin journey',status:'BLOCKED',reason:'Owned native KR/FREE policy UI creation failed; no shared policy fallback'});flush('admin');await c.close();continue;}
 if(policy&&category){ await step(width,'native UI own product and options create',async()=>{
 await p.goto(base+'/admin/ecommerce/products/create');await p.waitForLoadState('networkidle');await p.locator('input[name=product_code]').first().fill(run+'P'+width);await p.locator('input[name="name[ko]"]').fill('제주 '+run+' 합성 '+width);
 const cat=p.locator(width===390?'.category-item-mobile':'.category-item').filter({hasText:categoryTitle});await cat.click();await p.getByRole('button',{name:/선택한 카테고리 추가/}).click();
 await p.locator('input[name=list_price]:visible').fill('20000');await p.locator('input[name=selling_price]:visible').fill('12000');await p.locator('input[name=selling_price]:visible').blur();await p.waitForTimeout(500);await p.getByRole('button',{name:/비과세/,exact:true}).click();await p.getByRole('button',{name:'판매중',exact:true}).click();await p.getByRole('button',{name:'전시중',exact:true}).click();
 await p.getByRole('button',{name:/옵션그룹 추가/}).click();await p.locator('input[name="option_input_name_0[ko]"]').fill('출발');await p.waitForTimeout(400);await p.locator('input[placeholder="옵션값을 쉼표(,)로 구분하여 입력"]').fill('합성 A');await p.locator('input[placeholder="옵션값을 쉼표(,)로 구분하여 입력"]').press('Enter');await expect(p.getByRole('dialog')).toBeVisible();await p.getByRole('dialog').locator('input[type=text]').nth(0).fill('합성 A');await p.getByRole('dialog').locator('input[type=text]').nth(1).fill('Synthetic A');await p.getByRole('dialog').getByRole('button',{name:/추가/,exact:true}).click();await expect(p.getByRole('dialog')).toHaveCount(0);await p.locator('input[class*=min-w-][placeholder=""]').fill('합성 B');await p.locator('input[class*=min-w-][placeholder=""]').press('Enter');await expect(p.getByRole('dialog')).toBeVisible();await p.getByRole('dialog').locator('input[type=text]').nth(0).fill('합성 B');await p.getByRole('dialog').locator('input[type=text]').nth(1).fill('Synthetic B');await p.getByRole('dialog').getByRole('button',{name:/추가/,exact:true}).click();await p.getByRole('button',{name:/옵션 생성/,exact:true}).click();await p.waitForTimeout(500);await shot(p,m,'product-after-options');
 await expect(p.locator(width===390?'#option_table_mobile':'#option_table_desktop')).toBeVisible();
 const opts=p.locator(width===390?'#option_table_mobile':'#option_table_desktop').locator('input[type=number]:visible');console.log('option visible number count',width,await opts.count());
 await opts.nth(0).fill('20000');await opts.nth(1).fill('12000');await opts.nth(2).fill('5');await opts.nth(2).blur();await opts.nth(7).fill('20000');await opts.nth(8).fill('10000');await opts.nth(9).fill('5');await opts.nth(9).blur();await p.waitForTimeout(500);await p.locator('input[name=product_code]:visible').first().fill(run+'P'+width);await p.locator('input[name=list_price]:visible').fill('20000');await p.locator('input[name=selling_price]:visible').fill('12000');await p.locator('input[name=selling_price]:visible').blur();await p.waitForTimeout(500);
 await p.getByRole('switch',{name:'use_default_shipping',exact:true}).click();await p.getByRole('button').filter({hasText:globalThis.policyTitle}).click();await shot(p,m,'native-product-form');
 const wait=p.waitForResponse(r=>r.url().endsWith(commerce+'/products')&&r.request().method()==='POST');await p.getByTestId('product-save').click();const r=await wait;const d=await r.json();if(r.status()!==201)console.log('product create rejected',r.status(),scrub(JSON.stringify({errors:d.errors,message:d.message})));expect(r.status()).toBe(201);product=d.data.id;owned.products.push({id:product,policy,category,width});flush('admin');return {id:product,http:201};
 },'admin');}
 if(!product){results.push({width,name:'travel registration departure customer discover cart',status:'BLOCKED',reason:'Native UI product/policy creation did not complete; API-only substitution forbidden'});flush('admin');}
 await c.close();
}
await finishTokens(await browser.newPage());await browser.close();flush('admin');process.exitCode=results.some(r=>r.status==='FAIL')?1:0;
