"""집계 단위별 수치와 실행 이력을 기록한다. screenshot/token cleanup을 기능 PASS에 더하지 않는다."""
import pathlib,json,hashlib,datetime
root=pathlib.Path(__file__).resolve().parents[2];out=root/'docs/symphony/evidence/W04_NATIVE_ADMIN'
names=['admin','catalogue','public','support','journey-1440','recovery','owner-recovery','inactive','access-decline','quota','multiitem','mobile-inspection-final']
rows=[]
for name in names:
 j=json.loads((out/(name+'.json')).read_text());checks=[r for r in j['results'] if r.get('width') in [390,1440] and r.get('status') in ['PASS','FAIL','NOT_RUN','BLOCKED'] and not r['name'].startswith(('privacy OCR','horizontal overflow'))];rows.append({'report':name+'.json','unit':'named bounded check; not unique HTTP request or fixture count','checks':checks,'counts':{s:sum(r['status']==s for r in checks)for s in ['PASS','FAIL','NOT_RUN','BLOCKED']}})
# 390 core journey lives in preserved initial report;1440 initial failures are NOT hidden.
j=json.loads((out/'journey-initial-harness.json').read_text());checks=[r for r in j['results'] if r.get('width')==390 and not r['name'].startswith('privacy OCR')];rows.append({'report':'journey-initial-harness.json','selectedWidth':390,'unit':'native ordinary transaction checks','checks':checks,'counts':{s:sum(r['status']==s for r in checks)for s in ['PASS','FAIL','NOT_RUN','BLOCKED']}})
ledger=json.loads((out/'fixtures.json').read_text());counts={k:len(v)for k,v in ledger.items()};tokens=json.loads((out/'final-token-audit.json').read_text());cleanup=json.loads((out/'cleanup-counts.json').read_text())
summary={'observedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'reports':rows,'fixtureUnits':counts,'UIProductCreate':2,'UICategoryCreate':2,'UIPolicyCreate':2,'UIProductOptionCreate':4,'APIPaginationProductSetup':13,'tokenUnits':{'issuedDistinct':tokens['issuedDistinct'],'finalAudited401':sum(x['nativeRequery']==401 for x in tokens['audited']),'suppliedHandoffRetained':len(tokens['providedHandoff'])},'cleanup':cleanup,'nativeInternalHelpers':{'unique':1,'peakIncludingLead':2,'task':'source_binding reused for read-only source/public/packaging review','officialChildren':0,'canonicalValidation':'NOT_RUN'},'overlappingReportsNotSummed':True,'historicalFailuresRetained':True}
(out/'summary-counts.json').write_text(json.dumps(summary,ensure_ascii=False,indent=2)+'\n')
recorded=[json.loads(f.read_text()) for f in sorted(out.glob('*-command.json'))]
early=[{'command':['node','tests/W04_NATIVE_ADMIN/'+n+'.mjs'],'exit_code':c,'provenance':'Actual lead native shell run before exact-start archiver; retained reports and diagnostics. Current safe script hash is final version, not claimed as exact earlier executed version.'}for n,c in [('inspect',0),('create',0),('policy-diagnostic',0),('support-recheck',0),('pagination-fixtures',0),('public',0),('catalogue-diagnostic',0),('catalogue',0),('journey-recheck',1),('menu-diagnostic',0)]]
commands={'sourceSHA':'fa5523175ac494cfbd13bbf89bf06b3ec91835a6','workingDirectory':str(root),'runtime':'http://127.0.0.1:18871','browser':'Chromium156.0.8078.4','viewports':[{'width':390,'height':1000,'hasTouch':True,'isMobile':True},{'width':1440,'height':1000,'hasTouch':False,'isMobile':False}],'earlyExecutionSummary':early,'exactStartingArchives':recorded,'setup':['git fetch origin feat/g7-travel-lab-c7ae42d1','git checkout --detach fa5523175ac494cfbd13bbf89bf06b3ec91835a6','Own ignored @playwright/test dependency install; existing Chromium binary used'],'nonBrowser':['PYTHONDONTWRITEBYTECODE=1 python3 tests/W04_NATIVE_ADMIN/source-binding.py before (exit0)','PYTHONDONTWRITEBYTECODE=1 python3 tests/W04_NATIVE_ADMIN/source-binding.py after (see source-binding.json)','python3 tests/W04_NATIVE_ADMIN/build-matrix.py','python3 tests/W04_NATIVE_ADMIN/privacy-scan.py','python3 tests/W04_NATIVE_ADMIN/package-summary.py'],'archiveDependencyNote':'final-status starting archive did not include newly-created audit-api.mjs; final manifest supplies its unchanged safe final version. Later actor-effects archive includes it.', 'nativeCI':'NOT_RUN','earlyFailedAttempts':'Named sanitized *harness.json / inactive*failed.json / inactive-ui-toggle-witness.json retained; no fabricated exact-start archives.'}
(out/'commands.json').write_text(json.dumps(commands,ensure_ascii=False,indent=2)+'\n')
files=[f for f in(root/'tests/W04_NATIVE_ADMIN').rglob('*') if f.is_file()and not any(p in f.parts for p in ['.private','node_modules','__pycache__'])and f.name!='package.json'];(out/'safe-scripts-manifest.json').write_text(json.dumps({'files':[{'path':str(f.relative_to(root)),'sha256':hashlib.sha256(f.read_bytes()).hexdigest()}for f in sorted(files)],'label':'Final safe harness versions; exact starting executed versions only in commands/executed-scripts'},indent=2)+'\n');print(json.dumps({'fixtureUnits':counts,'tokenDistinct':tokens['issuedDistinct'],'reportGroups':len(rows)}))
