import fs from 'node:fs';import {base,out,travel,context,browser,expect,shot,step,flush,results} from './common.mjs';
const f=JSON.parse(fs.readFileSync(out+'/pagination-query.json'));
for(const width of [390,1440]){const {p,c,m}=await context(width);const filters=async()=>{if(width===390&&!await p.getByTestId('search-filters').isVisible())await p.getByTestId('filters-toggle').click();await expect(p.getByTestId('search-filters')).toBeVisible();};const ready=async()=>{await expect(p.getByTestId('catalog-loading')).toHaveCount(0);};const response=()=>p.waitForResponse(r=>r.url().includes(travel+'/catalog?')&&r.request().method()==='GET');
await step(width,'own thirteen API fixtures real UI date price filters URL reload',async()=>{await p.goto(base+'/travel/search?q='+f.marker);await ready();await filters();for(const [id,v]of [['filter-date_from','2026-12-24'],['filter-date_to','2026-12-26'],['filter-min_price','11000'],['filter-max_price','13000']])await p.getByTestId(id).fill(v);const w=response();await p.getByTestId('filter-apply').click();const r=await w;expect(r.status()).toBe(200);const d=(await r.json()).data;expect(d.pagination.total).toBe(13);expect(d.data.every(x=>f.productIds.includes(x.id))).toBe(true);await p.reload();await filters();await expect(p.getByTestId('filter-date_to')).toHaveValue('2026-12-26');await expect(p.getByTestId('filter-max_price')).toHaveValue('13000');await shot(p,m,'native-own-filters');return {total:13,query:new URL(p.url()).search};},'public');
for(const [label,sort]of [['낮은 가격순','price_asc'],['높은 가격순','price_desc'],['출발 임박순','departure_asc'],['추천순','recommended']])await step(width,'own UI sort '+sort,async()=>{await p.getByTestId('sort-select').click();const w=response();await p.getByRole('option',{name:label,exact:true}).click();const r=await w;expect(r.status()).toBe(200);const d=(await r.json()).data;expect(new URL(p.url()).searchParams.get('q')).toBe(f.marker);expect(new URL(p.url()).searchParams.get('sort')).toBe(sort);if(sort.startsWith('price')){const prices=d.data.map(x=>x.from_price);expect(prices).toEqual([...prices].sort((a,b)=>sort==='price_asc'?a-b:b-a));}return {ids:d.data.map(x=>x.id),sort};},'public');
await step(width,'own UI pagination12 plus1 next preserves filters sort reload',async()=>{await expect(p.getByTestId('trip-card')).toHaveCount(12);const first=(await p.getByTestId('trip-card').allTextContents());const w=response();await p.getByRole('navigation',{name:'페이지 이동'}).getByRole('button',{name:'다음 페이지',exact:true}).click();const d=(await(await w).json()).data;expect(d.data).toHaveLength(1);expect(f.productIds).toContain(d.data[0].id);await expect(p.getByTestId('trip-card')).toHaveCount(1);expect(new URL(p.url()).searchParams.get('page')).toBe('2');await p.reload();await expect(p.getByTestId('trip-card')).toHaveCount(1);await shot(p,m,'own-pagination-page2');return {firstPageCount:first.length,secondIds:d.data.map(x=>x.id),total:13,setup:'Native API fixture ONLY; UI CREATE proved separately'};},'public');
await step(width,'native empty and reset action',async()=>{await p.goto(base+'/travel/search?q=W04N_NO_MATCH');await expect(p.getByTestId('catalog-empty')).toBeVisible();await shot(p,m,'native-empty');await p.getByTestId('catalog-empty').getByRole('button').click();await expect(p.getByTestId('trip-card').first()).toBeVisible();return {http:200,reset:true};},'public');
await step(width,'actual loading held GET abort error retry actual200',async()=>{let release;const gate=new Promise(resolve=>release=resolve);await p.route('**'+travel+'/catalog?**',async r=>{await gate;await r.abort('failed');});await p.goto(base+'/travel/search');await expect(p.getByTestId('catalog-loading')).toBeVisible();await shot(p,m,'native-loading');release();await expect(p.getByTestId('catalog-error')).toBeVisible();await shot(p,m,'native-error');await p.unroute('**'+travel+'/catalog?**');const w=response();await p.getByTestId('catalog-retry').click();expect((await w).status()).toBe(200);await expect(p.getByTestId('catalog-error')).toHaveCount(0);return {injection:'Browser network held/aborted GET only; no fake response or backend outage',retry:200};},'public');await c.close();}
flush('public');await browser.close();process.exitCode=results.some(x=>x.status==='FAIL')?1:0;
