import './review-source.mjs';
import {chromium,expect,request} from '@playwright/test';import fs from 'node:fs';
const a=JSON.parse(fs.readFileSync(process.env.W03_ACCESS_FILE));const base=a.base_url,dir='docs/symphony/evidence/W03';const api=await request.newContext({baseURL:base,extraHTTPHeaders:{Accept:'application/json',Authorization:'Bearer '+a.admin.bearer_token}});const prefix='/api/modules/sirsoft-ecommerce/admin';const run='W03-P-'+Date.now();const results=[],metrics=[];let fixture;
const b=await chromium.launch();const scrub=s=>{for(const role of ['member','other_member','admin'])for(const v of Object.values(a[role]))if(typeof v==='string')s=String(s).replaceAll(v,'[private]');return s;};
const flush=()=>fs.writeFileSync(dir+'/commerce-results.json',JSON.stringify({tested_sha:'28ada286c1c34606741bcfe4f9d12e06ac50af30',run,fixture,results,metrics},null,2));
async function step(width,name,fn){try{const detail=await fn();results.push({width,name,status:'PASS',detail});console.log(width,name,'PASS');}catch(e){results.push({width,name,status:'FAIL',error:scrub(e.message).slice(0,1200)});console.log(width,name,'FAIL',scrub(e.message).split('\n')[0]);}flush();}
const source=(await (await api.get(prefix+'/products/1')).json()).data;
const categoryPayload={name:{ko:run+' 합성 분류',en:run+' synthetic category'},slug:run.toLowerCase(),is_active:true};const cr=await api.post(prefix+'/categories',{data:categoryPayload});const cd=await cr.json();const category=cd.data;if(!category?.id){console.log('category fixture failed',cr.status());await api.dispose();await b.close();process.exit(1);}results.push({width:0,name:'NEW own category fixture',status:'PASS',detail:{id:category.id,http:cr.status()}});
const payload={name:{ko:run+' 합성 상품',en:run+' Synthetic product'},product_code:run.replaceAll('-',''),sku:run,category_ids:[category.id],list_price:20000,selling_price:12000,stock_quantity:5,sales_status:'on_sale',display_status:'hidden',tax_status:'tax_free',shipping_policy_id:source.shipping_policy_id,has_options:false,options:[{option_code:run+'-OPT',option_name:{ko:'W03 합성 출발 옵션',en:'W03 synthetic departure'},option_values:[{key:{ko:'출발일',en:'Departure'},value:{ko:'2026-11-30',en:'2026-11-30'}}],list_price:20000,selling_price:12000,stock_quantity:5,is_active:true,is_default:true}]};
await step(0,'NEW own commerce fixture via real native API',async()=>{const r=await api.post(prefix+'/products',{data:payload});const d=await r.json();if(r.status()!==201)results.push({width:0,name:'own product creation rejection',status:'OBSERVED',detail:{status:r.status(),errors:d.errors,message:d.message}});expect(r.status()).toBe(201);fixture={id:d.data.id,product_code:d.data.product_code};return {status:201,...fixture};});
if(fixture)for(const width of [390,1440]){
 const c=await b.newContext({locale:'ko-KR',viewport:{width,height:1000}}),p=await c.newPage();p.setDefaultTimeout(10000);const m={width,pageErrors:[],consoleErrors:[],requests:[],overflow:[]};metrics.push(m);p.on('pageerror',e=>m.pageErrors.push(scrub(e.message)));p.on('console',e=>{if(e.type()==='error')m.consoleErrors.push(scrub(e.text()));});p.on('request',r=>{if(new URL(r.url()).pathname.startsWith('/api/'))m.requests.push({path:new URL(r.url()).pathname,method:r.method(),nativeBearer:r.headers().authorization?.startsWith('Bearer ')??false});});
 await p.goto(base+'/login');await p.locator('#travel-login-email').fill(a.admin.email);await p.locator('#travel-login-password').fill(a.admin.password);const login=p.waitForResponse(r=>new URL(r.url()).pathname==='/api/auth/login'&&r.request().method()==='POST');await p.locator('form button[type=submit]').click();expect((await login).status()).toBe(200);await expect(p).not.toHaveURL(/\/login/);
 await step(width,'native UI edit own product price/options and persist',async()=>{await p.goto(base+'/admin/ecommerce/products/'+fixture.product_code+'/edit');await expect(p.locator('input[name=selling_price]').first()).toBeEnabled({timeout:15000});const before=await p.locator('input[name=selling_price]').first().inputValue();await p.locator('input[name=selling_price]').first().fill(String(12500+width));const save=p.waitForResponse(r=>r.request().method()==='PUT'&&r.url().includes('/admin/products/'));await p.getByTestId('product-save').click();const r=await save;expect(r.status()).toBe(200);await p.goto(base+'/admin/ecommerce/products/'+fixture.product_code+'/edit');await expect(p.locator('input[name=selling_price]').first()).toHaveValue(String(12500+width));await p.screenshot({path:dir+'/commerce-own-saved-'+width+'.png',fullPage:true,mask:[p.locator('input,textarea'),p.getByText(a.admin.email,{exact:false})]});const o=await p.evaluate(()=>({viewport:innerWidth,document:document.documentElement.scrollWidth}));m.overflow.push(o);expect(o.document).toBeLessThanOrEqual(width);const d=(await (await api.get(prefix+'/products/'+fixture.id)).json()).data;return {before,after:d.selling_price,options:d.options?.map(o=>({id:o.id,selling_price:o.selling_price,stock_quantity:o.stock_quantity}))};});
 await step(width,'NEW product travel metadata onboarding availability',async()=>{const r=await api.patch('/api/modules/raonslab-travel_lab/admin/catalog/'+fixture.id,{data:{published:false,region:'jeju',theme:'nature',duration_days:1,summary:{ko:'W03 독립 합성',en:'W03 synthetic'}}});results.push({width,name:'travel onboarding observed native API',status:'OBSERVED',detail:{status:r.status(),id:fixture.id}});expect(r.status()).toBe(200);});
 await c.close();
}
if(fixture){const d=(await (await api.get(prefix+'/products/'+fixture.id)).json()).data;const data={...payload,display_status:'hidden',options:(d.options??[]).map(o=>({...payload.options[0],id:o.id,selling_price:o.selling_price}))};const r=await api.put(prefix+'/products/'+fixture.id,{data});results.push({width:0,name:'cleanup retain own hidden commerce fixture',status:r.ok()?'PASS':'FAIL',detail:{id:fixture.id,http:r.status()}});}
const cclean=await api.put(prefix+'/categories/'+category.id,{data:{...categoryPayload,is_active:false}});results.push({width:0,name:'cleanup own category inactive',status:cclean.ok()?'PASS':'FAIL',detail:{id:category.id,http:cclean.status()}});await b.close();await api.dispose();flush();process.exitCode=results.some(r=>r.status==='FAIL')?1:0;
