import './review-source.mjs';
import { chromium, expect } from '@playwright/test';
import fs from 'node:fs';import crypto from 'node:crypto';
const SHA='28ada286c1c34606741bcfe4f9d12e06ac50af30';
const access=JSON.parse(fs.readFileSync(process.env.W03_ACCESS_FILE,'utf8'));
const base=process.env.W03_BASE_URL||access.base_url;
if(new URL(base).hostname!=='127.0.0.1')throw new Error('Loopback preview required');
const out='docs/symphony/evidence/W03';fs.mkdirSync(out,{recursive:true});
const run='W03-'+Date.now();const results=[];const metrics=[];const fixtures=[];
const scrub=s=>{s=String(s);for(const role of ['member','other_member','admin'])for(const v of Object.values(access[role]))if(typeof v==='string')s=s.replaceAll(v,'[private]');return s.replace(/Bearer\s+\S+/gi,'Bearer [private]');};
const b=await chromium.launch();
async function context(width,role){const c=await b.newContext({locale:'ko-KR',viewport:{width,height:1000}});const p=await c.newPage();p.setDefaultTimeout(8000);p.setDefaultNavigationTimeout(15000);const m={width,role,pageErrors:[],consoleErrors:[],httpErrors:[],requests:[],overflow:[]};metrics.push(m);p.on('pageerror',e=>m.pageErrors.push(scrub(e.message)));p.on('console',e=>{if(e.type()==='error')m.consoleErrors.push(scrub(e.text()).slice(0,600));});p.on('request',r=>{const path=new URL(r.url()).pathname;if(path.startsWith('/api/'))m.requests.push({path,method:r.method(),nativeBearer:r.headers().authorization?.startsWith('Bearer ')??false});});p.on('response',r=>{if(r.status()>=400)m.httpErrors.push({path:new URL(r.url()).pathname,status:r.status()});});return {c,p,m};}
async function step(width,name,fn){try{const detail=await fn();results.push({width,name,status:'PASS',detail});console.log(width,name,'PASS');return true;}catch(e){results.push({width,name,status:'FAIL',error:scrub(e.message).slice(0,1200)});console.log(width,name,'FAIL',scrub(e.message).split('\n')[0]);return false;}finally{fs.writeFileSync(out+'/journey-results.json',JSON.stringify({tested_sha:SHA,run,results,metrics,fixtures},null,2));}}
async function login(p,role){await p.goto(base+'/login');await p.locator('#travel-login-email').fill(access[role].email);await p.locator('#travel-login-password').fill(access[role].password);const response=p.waitForResponse(r=>new URL(r.url()).pathname==='/api/auth/login'&&r.request().method()==='POST');await p.locator('form button[type=submit]').click();expect((await response).status()).toBe(200);await expect(p).not.toHaveURL(/\/login/);}
async function shot(p,width,name,m){await p.screenshot({path:`${out}/${name}-${width}.png`,fullPage:true,mask:[p.locator('input,textarea'),...['member','other_member','admin'].map(role=>p.getByText(access[role].email,{exact:false}))]});m.overflow.push({name,...await p.evaluate(()=>({viewport:innerWidth,document:document.documentElement.scrollWidth,overflow:document.documentElement.scrollWidth>innerWidth}))});expect(m.overflow.at(-1).overflow).toBe(false);}
const travel='/api/modules/raonslab-travel_lab';
async function api(p,path,method='GET',data,role='member'){const r=await p.request.fetch(base+travel+path,{method,headers:{Accept:'application/json',Authorization:'Bearer '+access[role].bearer_token},...(data?{data}:{})});return {status:r.status(),body:await r.json()};}

for(const width of (process.env.W03_WIDTHS||'390,1440').split(',').map(Number)){
 const {p,c,m}=await context(width,'member');const adm=await context(width,'admin');let inquiryId,questionId,cartId;
 if(!await step(width,'native UI login',()=>login(p,'member'))){await c.close();await adm.c.close();continue;}
 await step(width,'empty cart',async()=>{await p.goto(base+'/travel/cart');await expect(p.getByText('아직 담은 여행이 없어요')).toBeVisible();await shot(p,width,'cart-empty',m);});
 await step(width,'departure/people/real cart add',async()=>{await p.goto(base+'/travel/products/1');await p.getByTestId('departure-option').first().click();await p.getByTestId('people-increase').click();const response=p.waitForResponse(r=>r.url().endsWith(travel+'/cart')&&r.request().method()==='POST');await p.getByTestId('add-to-cart').click();const r=await response;expect(r.status()).toBe(201);const data=await r.json();cartId=data.data.items[0].id;expect(data.data.items[0].quantity).toBe(2);await expect(p.getByTestId('go-cart')).toBeVisible();await shot(p,width,'cart-added',m);return {status:r.status(),cartId};});
 await step(width,'cart change/remove modal/re-add',async()=>{await p.getByTestId('go-cart').click();await expect(p.getByTestId('cart-qty-increase')).toBeVisible();let response=p.waitForResponse(r=>r.url().endsWith(travel+'/cart/'+cartId)&&r.request().method()==='PATCH');await p.getByTestId('cart-qty-increase').click();expect((await (await response).json()).data.items[0].quantity).toBe(3);await expect(p.getByTestId('cart-qty')).toHaveText('3명');await expect(p.getByTestId('cart-qty-decrease')).toBeEnabled();response=p.waitForResponse(r=>r.url().endsWith(travel+'/cart/'+cartId)&&r.request().method()==='PATCH');await p.getByTestId('cart-qty-decrease').click();expect((await (await response).json()).data.items[0].quantity).toBe(2);await p.getByTestId('cart-remove').click();await expect(p.getByRole('dialog')).toBeVisible();await shot(p,width,'cart-remove-modal',m);console.log('modal buttons',scrub(await p.getByRole('dialog').innerText()));await p.getByTestId('cart-remove-confirm').click();await expect(p.getByText('아직 담은 여행이 없어요')).toBeVisible();await p.goto(base+'/travel/products/1');await p.getByTestId('departure-option').first().click();await p.getByTestId('add-to-cart').click();await p.getByTestId('go-cart').click();await expect(p.getByTestId('contact-name')).toBeVisible();});
 await step(width,'trial acknowledgement/contact/response-loss idempotency retry',async()=>{await p.goto(base+'/travel/cart');await expect(p.getByTestId('contact-name')).toBeVisible();await expect(p.getByTestId('submit-inquiry')).toBeDisabled();await p.getByTestId('contact-name').fill(run+' synthetic '+width);await p.getByTestId('contact-phone').fill('000-0000-0000');await p.getByTestId('ack-test').check();await expect(p.getByTestId('submit-inquiry')).toBeEnabled();await shot(p,width,'cart-trial-contact',m);
 let original,key1,key2,body1,body2;let captured=false;
 await p.route('**'+travel+'/inquiries',async route=>{if(route.request().method()==='POST'&&!captured){captured=true;body1=route.request().postDataJSON();key1=body1.idempotency_key;const real=await route.fetch();expect(real.status()).toBe(201);original=(await real.json()).data;inquiryId=original.id;fixtures.push({width,inquiryId,reference:original.reference});await route.abort('failed');}else{if(route.request().method()==='POST'){body2=route.request().postDataJSON();key2=body2.idempotency_key;}await route.continue();}});
 await p.getByTestId('submit-inquiry').click();await expect(p.getByTestId('submit-inquiry')).toBeEnabled();expect(captured).toBeTruthy();await shot(p,width,'inquiry-fault-injection',m);const replay=p.waitForResponse(r=>r.url().endsWith(travel+'/inquiries')&&r.request().method()==='POST');await p.getByTestId('submit-inquiry').click();const r=await replay;results.push({width,name:'retry payload evidence',status:'OBSERVED',detail:{body1:{...body1,idempotency_key:crypto.createHash('sha256').update(key1).digest('hex')},body2:{...body2,idempotency_key:crypto.createHash('sha256').update(key2).digest('hex')},status:r.status(),response:await r.json()}});await p.unroute('**'+travel+'/inquiries');expect(r.status()).toBe(200);const retried=(await r.json()).data;expect(retried.id).toBe(original.id);expect(key2).toBe(key1);inquiryId=retried.id;fixtures.push({width,inquiryId,reference:retried.reference,keySha256:crypto.createHash('sha256').update(key1).digest('hex')});await p.unroute('**'+travel+'/inquiries');await expect(p).toHaveURL(new RegExp('/travel/requests/'+inquiryId));await shot(p,width,'inquiry-detail',m);return {inquiryId,replayStatus:200,keyPreserved:true,faultInjection:'real upstream201 response intentionally dropped; replay real200 same ID'};});
 await step(width,'normal UI submit with real201 navigation',async()=>{await p.goto(base+'/travel/products/2');await p.getByTestId('departure-option').first().click();await p.getByTestId('add-to-cart').click();await p.getByTestId('go-cart').click();await p.getByTestId('contact-name').fill(run+' normal '+width);await p.getByTestId('contact-phone').fill('000-0000-0000');await p.getByTestId('ack-test').check();const response=p.waitForResponse(r=>r.url().endsWith(travel+'/inquiries')&&r.request().method()==='POST');await p.getByTestId('submit-inquiry').click();const r=await response;expect(r.status()).toBe(201);inquiryId=(await r.json()).data.id;fixtures.push({width,inquiryId,kind:'normal'});await expect(p).toHaveURL(new RegExp('/travel/requests/'+inquiryId));await expect(p.getByTestId('detail-status')).toContainText('테스트 접수');await shot(p,width,'normal-inquiry-detail',m);});
 await step(width,'my requests list/detail',async()=>{expect(inquiryId).toBeTruthy();await p.goto(base+'/travel/requests');await expect(p.getByText('요청 #'+inquiryId,{exact:false}).first()).toBeVisible();await shot(p,width,'my-requests',m);});
 await step(width,'native admin UI login/lookup/state+note',async()=>{expect(inquiryId).toBeTruthy();await login(adm.p,'admin');await adm.p.goto(base+'/admin/travel-lab/inquiries');await expect(adm.p.getByRole('heading',{name:'여행 문의',exact:true})).toBeVisible();await expect(adm.p.getByText('TL-'+String(inquiryId).padStart(8,'0'),{exact:true})).toBeVisible();await shot(adm.p,width,'admin-inquiries-list',adm.m);await adm.p.goto(base+'/admin/travel-lab/inquiries/'+inquiryId);await expect(adm.p.locator('textarea')).toBeVisible();await adm.p.locator('textarea').fill(run+' synthetic note');await adm.p.getByRole('button',{name:'검토 중',exact:true}).click();const response=adm.p.waitForResponse(r=>r.url().endsWith(travel+'/admin/inquiries/'+inquiryId)&&r.request().method()==='PATCH');await adm.p.getByRole('button',{name:/저장/}).click();expect((await response).status()).toBe(200);await expect(adm.p.getByRole('button',{name:'테스트 수락',exact:true})).toBeVisible();await adm.p.getByRole('button',{name:'테스트 수락',exact:true}).click();const accepted=adm.p.waitForResponse(r=>r.url().endsWith(travel+'/admin/inquiries/'+inquiryId)&&r.request().method()==='PATCH');await adm.p.getByRole('button',{name:/저장/}).click();expect((await accepted).status()).toBe(200);await shot(adm.p,width,'admin-test-accepted',adm.m);});
 await step(width,'owner reload TEST_ACCEPTED/test-only notice',async()=>{expect(inquiryId).toBeTruthy();await p.goto(base+'/travel/requests/'+inquiryId);await expect(p.getByTestId('detail-status')).toContainText('테스트 수락');await expect(p.getByText(/실제 예약·결제/).first()).toBeVisible();await shot(p,width,'owner-test-accepted',m);});
 await step(width,'real logout/relogin persistence',async()=>{if(width===390)await p.getByTestId('menu-toggle').click();await p.getByRole('button',{name:'로그아웃',exact:true}).click();await expect(p).toHaveURL(/\/login/);await expect(p.locator('#travel-login-email')).toBeVisible();await login(p,'member');await p.goto(base+'/travel/requests/'+inquiryId);await expect(p.getByText('요청 #'+inquiryId,{exact:false}).first()).toBeVisible();});
 await step(width,'notice FAQ own question create/requery',async()=>{await p.goto(base+'/travel/help');await p.getByTestId('notice-item').first().click();await shot(p,width,'notice-open',m);await p.getByTestId('help-tab-faq').click();await p.getByTestId('faq-item').first().click();await shot(p,width,'faq-open',m);await p.getByTestId('help-tab-questions').click();await p.getByTestId('question-title').fill(run+' question '+width);await p.getByTestId('question-content').fill('합성 W03 독립 검증 문의입니다. 실제 예약이 아닙니다.');const response=p.waitForResponse(r=>r.url().endsWith(travel+'/support/questions')&&r.request().method()==='POST');await p.getByTestId('question-submit').click();const r=await response;expect(r.status()).toBe(201);questionId=(await r.json()).data.id;fixtures.push({width,questionId});await p.reload();await expect(p.getByTestId('question-item').filter({hasText:run+' question '+width})).toBeVisible();await p.getByTestId('question-item').filter({hasText:run+' question '+width}).click();await shot(p,width,'own-question',m);});
 await step(width,'cleanup own cancel allocation',async()=>{if(!inquiryId){const owned=await api(p,'/inquiries');const f=owned.body.data?.data?.find(x=>x.contact?.name===run+' synthetic '+width);inquiryId=f?.id;}expect(inquiryId).toBeTruthy();await p.goto(base+'/travel/requests/'+inquiryId);await p.getByTestId('cancel-request').click();await expect(p.getByRole('dialog')).toBeVisible();console.log('cancel modal',scrub(await p.getByRole('dialog').innerText()));await p.getByTestId('cancel-confirm').click();await expect(p.getByTestId('detail-status')).toContainText('취소');return {inquiryId};});
 await step(width,'cleanup response-loss own inquiry via native UI',async()=>{const f=fixtures.find(f=>f.width===width&&f.reference);expect(f).toBeTruthy();await p.goto(base+'/travel/requests/'+f.inquiryId);await p.getByTestId('cancel-request').click();await p.getByTestId('cancel-confirm').click();await expect(p.getByTestId('detail-status')).toContainText('취소');return {inquiryId:f.inquiryId};});
 await c.close();await adm.c.close();
}
await b.close();fs.writeFileSync(out+'/journey-results.json',JSON.stringify({tested_sha:SHA,run,results,metrics,fixtures},null,2));

process.exitCode=results.some(r=>r.status==='FAIL')?1:0;
