import './review-source.mjs';
import {chromium,expect} from '@playwright/test';import fs from 'node:fs';
const a=JSON.parse(fs.readFileSync(process.env.W03_ACCESS_FILE)),dir='docs/symphony/evidence/W03',base=a.base_url,j=JSON.parse(fs.readFileSync(dir+'/journey-results.json')),f=JSON.parse(fs.readFileSync(dir+'/commerce-results.json')).fixture,b=await chromium.launch(),results=[],metrics=[];
const flush=()=>fs.writeFileSync(dir+'/regression-results.json',JSON.stringify({tested_sha:j.tested_sha,results,metrics},null,2));
const scrub=s=>{for(const role of ['member','other_member','admin'])for(const v of Object.values(a[role]))if(typeof v==='string')s=String(s).replaceAll(v,'[private]');return s;};
async function login(p,role){await p.goto(base+'/login');await p.locator('#travel-login-email').fill(a[role].email);await p.locator('#travel-login-password').fill(a[role].password);const r=p.waitForResponse(r=>new URL(r.url()).pathname==='/api/auth/login'&&r.request().method()==='POST');await p.locator('form button[type=submit]').click();expect((await r).status()).toBe(200);await expect(p).not.toHaveURL(/\/login/);}
async function step(width,name,fn){try{results.push({width,name,status:'PASS',detail:await fn()});console.log(width,name,'PASS');}catch(e){results.push({width,name,status:'FAIL',error:scrub(e.message).slice(0,1200)});console.log(width,name,'FAIL');}flush();}
async function shot(p,width,name){await p.screenshot({path:dir+'/'+name+'-'+width+'.png',fullPage:true,mask:[p.locator('input,textarea'),...['member','other_member','admin'].map(role=>p.getByText(a[role].email,{exact:false}))]});}
for(const width of [390,1440]){
 const c=await b.newContext({locale:'ko-KR',viewport:{width,height:1000}}),p=await c.newPage();p.setDefaultTimeout(12000);const m={width,pageErrors:[],consoleErrors:[]};metrics.push(m);p.on('pageerror',e=>m.pageErrors.push(scrub(e.message)));p.on('console',e=>{if(e.type()==='error')m.consoleErrors.push(scrub(e.text()));});await login(p,'member');
 await step(width,'real logout/relogin persistence corrected locator',async()=>{const own=j.fixtures.find(x=>x.width===width&&x.kind==='normal');await p.goto(base+'/travel/requests/'+own.inquiryId);await expect(p.getByTestId('detail-status')).toContainText('취소');if(width===390)await p.getByTestId('menu-toggle').click();const logout=p.waitForResponse(r=>new URL(r.url()).pathname==='/api/auth/logout'&&r.request().method()==='POST');await p.getByRole('button',{name:'로그아웃',exact:true}).click();expect((await logout).status()).toBe(200);await expect(p).toHaveURL(/\/login/);await login(p,'member');await p.goto(base+'/travel/requests/'+own.inquiryId);await expect(p.getByText('요청 #'+own.inquiryId,{exact:false}).first()).toBeVisible();await expect(p.getByTestId('detail-status')).toContainText('취소');await shot(p,width,'relogin-persistence');return {inquiryId:own.inquiryId,status:'CANCELLED',nativeLogin200:true,nativeLogout200:true};});
 await c.close();const ca=await b.newContext({locale:'ko-KR',viewport:{width,height:1000}}),pa=await ca.newPage();pa.setDefaultTimeout(12000);pa.on('pageerror',e=>m.pageErrors.push(scrub(e.message)));pa.on('console',e=>{if(e.type()==='error')m.consoleErrors.push(scrub(e.text()));});await login(pa,'admin');
 await step(width,'own native commerce valid price save/reload diagnostic',async()=>{expect(f).toBeTruthy();await pa.goto(base+'/admin/ecommerce/products/'+f.product_code+'/edit');const field=pa.locator('input[name=selling_price]').first();await expect(field).toBeEnabled();const before=await field.inputValue(),value=width===390?'13000':'14000';await field.fill(value);await field.blur();await expect(field).toHaveValue(value);await shot(pa,width,'own-price-before-save');const saved=pa.waitForResponse(r=>r.request().method()==='PUT'&&r.url().includes('/admin/products/'));await pa.getByTestId('product-save').click();const response=await saved;expect(response.status()).toBe(200);const payload=response.request().postDataJSON(),reply=await response.json();await pa.goto(base+'/admin/ecommerce/products/'+f.product_code+'/edit');await expect(pa.locator('input[name=selling_price]').first()).toBeEnabled();await shot(pa,width,'own-price-after-save');const after=await pa.locator('input[name=selling_price]').first().inputValue();results.push({width,name:'own native saved price evidence',status:'OBSERVED',detail:{fixture:f.id,before,entered:value,wirePrice:payload.selling_price,wireOptions:payload.options?.map(o=>({id:o.id,selling_price:o.selling_price})),status:response.status(),responsePrice:reply.data?.selling_price,reloaded:after}});expect(after).toBe(value);});await ca.close();
}
await b.close();flush();process.exitCode=results.some(r=>r.status==='FAIL')?1:0;
