/** Native G7 layout dispatch, source-bound private question edit regression. */
import {afterEach,beforeAll,describe,expect,it,vi} from 'vitest';
import {createLayoutTest,screen,waitFor} from '@core/template-engine/__tests__/utils/layoutTestUtils';
import {registerTemplateComponents,loadLayout,flatten,translations,API_BASE} from '../helpers/travelTestKit';
let registry:any,t:ReturnType<typeof createLayoutTest>|undefined;
beforeAll(()=>{registry=registerTemplateComponents();});afterEach(()=>{t?.cleanup();t=undefined;});
async function render(isMine=true){t=createLayoutTest(flatten(loadLayout('travel/help.json')),{componentRegistry:registry,translations,locale:'ko',queryParams:{tab:'questions',question:'5'},initialState:{_global:{currentUser:{uuid:'member-one'}}}});t.mockApi('questions',{response:{success:true,data:{data:[],meta:{current_page:1,last_page:1}}}});t.mockApi('question_detail',{response:{success:true,data:{id:5,title:'합성 제목',content:'합성 본문',is_mine:isMine,answers:[]}}});await t.render();(window as any).G7Core.state.get=()=>t!.getState()._global;return t;}
describe('private question native edit UI',()=>{
 it('only the owner receives an edit control',async()=>{await render(false);expect(screen.queryByTestId('question-edit')).toBeNull();});
 it('edits title/content through native PATCH and refreshes the detail',async()=>{await render();await t!.user.click(screen.getByTestId('question-edit'));expect(screen.getByTestId('question-edit-title')).toHaveValue('합성 제목');expect(screen.getByTestId('question-edit-content')).toHaveValue('합성 본문');await t!.user.clear(screen.getByTestId('question-edit-title'));await t!.user.type(screen.getByTestId('question-edit-title'),'수정 제목');await t!.user.clear(screen.getByTestId('question-edit-content'));await t!.user.type(screen.getByTestId('question-edit-content'),'수정 본문');const original=globalThis.fetch;globalThis.fetch=vi.fn(async(url:any,init:any)=>String(url).endsWith(`${API_BASE}/support/questions/5`)&&init?.method==='PATCH'?new Response(JSON.stringify({success:true,data:{id:5,title:'수정 제목',content:'수정 본문',is_mine:true}}),{status:200,headers:{'Content-Type':'application/json'}}):original(url,init)) as any;await t!.user.click(screen.getByTestId('question-edit-save'));await waitFor(()=>{const call=vi.mocked(globalThis.fetch).mock.calls.find(([url,init])=>String(url).endsWith(`${API_BASE}/support/questions/5`)&&init?.method==='PATCH');expect(call).toBeDefined();expect(JSON.parse(String(call![1]!.body))).toEqual({title:'수정 제목',content:'수정 본문'});});await waitFor(()=>expect(screen.queryByTestId('question-edit-save')).toBeNull());});
 it('keeps typed input after server validation and allows cancel without a PATCH',async()=>{await render();await t!.user.click(screen.getByTestId('question-edit'));await t!.user.clear(screen.getByTestId('question-edit-title'));await t!.user.type(screen.getByTestId('question-edit-title'),'수정 제목');const original=globalThis.fetch;globalThis.fetch=vi.fn(async(url:any,init:any)=>String(url).endsWith(`${API_BASE}/support/questions/5`)&&init?.method==='PATCH'?new Response(JSON.stringify({message:'Validation failed',errors:{title:['검증 실패']}}),{status:422,headers:{'Content-Type':'application/json'}}):original(url,init)) as any;await t!.user.click(screen.getByTestId('question-edit-save'));await waitFor(()=>expect(screen.getByTestId('question-edit-error')).toHaveTextContent('검증 실패'));expect(screen.getByTestId('question-edit-title')).toHaveValue('수정 제목');expect(screen.getByTestId('question-edit-save')).not.toBeDisabled();const count=vi.mocked(globalThis.fetch).mock.calls.filter(([,i])=>i?.method==='PATCH').length;await t!.user.click(screen.getByTestId('question-edit-cancel'));expect(screen.queryByTestId('question-edit-save')).toBeNull();expect(vi.mocked(globalThis.fetch).mock.calls.filter(([,i])=>i?.method==='PATCH')).toHaveLength(count);});
});
