[global]
pid = /run/g7-product-fpm/php-fpm.pid
error_log = /srv/g7/current/storage/logs/php-fpm-error.log
daemonize = no

[g7-product]
user = ubuntu
group = www-data
listen = /run/g7-product-fpm/php-fpm.sock
listen.owner = ubuntu
listen.group = www-data
listen.mode = 0660

pm = dynamic
pm.max_children = 8
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 4
pm.max_requests = 500

chdir = /srv/g7/current
clear_env = yes
catch_workers_output = yes
decorate_workers_output = no

php_admin_value[error_log] = /srv/g7/current/storage/logs/php-fpm-worker.log
php_admin_value[memory_limit] = 256M
php_admin_value[post_max_size] = 25M
php_admin_value[upload_max_filesize] = 20M
php_admin_value[max_execution_time] = 900
php_admin_flag[log_errors] = on
