import fs from 'node:fs';import {base,out,travel,context,login,browser,expect,shot,api,step,flush,results,finishTokens} from './common.mjs';
const fixtures=JSON.parse(fs.readFileSync(out+'/admin.json')).owned.products;
for(const width of [390,1440]){const {p,c,m}=await context(width,'admin'),customer=await context(width,'member');await login(p,'admin');await login(customer.p,'member');const f=fixtures[width===390?0:1];
 await step(width,'settled native missing departure continuation and independent final read',async()=>{const q=await api(p,travel+'/admin/catalog/'+f.id,'GET',undefined,'admin');expect(q.status).toBe(200);const option=q.body.data.options[0],existing=q.body.data.departures.find(d=>d.product_option_id===option.id);let id=existing?.id;
 if(!existing){const wait=p.waitForResponse(r=>r.url().includes(travel+'/admin/catalog?')&&r.request().method()==='GET'&&new URL(r.url()).searchParams.get('page')==='1');await p.goto(base+'/admin/travel-lab?per_page=48');const r=await wait,j=(await r.json()).data;expect(r.status()).toBe(200);await expect.poll(()=>p.locator('.card-title').count()).toBe(j.data.length);const card=p.locator('.admin-card').filter({has:p.getByText(q.body.data.title,{exact:true})});await card.getByRole('button',{name:'출발일 추가',exact:true}).click();await p.getByTestId('departure_product_option_select').click();await p.getByRole('option').filter({hasText:new RegExp(' · '+option.id+' · ')}).click();await expect.poll(()=>p.evaluate(()=>G7Core.state.get().travelDepartureEdit.product_option_id)).toBe(option.id);
 for(const [testid,key,value] of [['departure_departure_date_input','departure_date','2026-12-15'],['departure_return_date_input','return_date','2026-12-17'],['departure_capacity_input','capacity','4']]){await p.getByTestId(testid).focus();await p.getByTestId(testid).fill(value);await p.getByTestId(testid).blur();await expect.poll(()=>p.evaluate(key=>G7Core.state.get().travelDepartureEdit[key],key)).toBe(key==='capacity'?Number(value):value);}
 const write=p.waitForResponse(r=>r.url().endsWith(travel+'/admin/catalog/'+f.id+'/departures')&&r.request().method()==='POST');await p.getByTestId('departure_save').click();const saved=await write;expect(saved.status()).toBe(200);id=(await saved.json()).data.id;await expect(p.getByRole('dialog')).toHaveCount(0);await shot(p,m,'departure-final-settled');}
 const detail=await api(customer.p,travel+'/catalog/'+f.id);expect(detail.status).toBe(200);expect(detail.body.data.from_price).toBe(13000);expect(detail.body.data.departures.some(d=>d.available===0&&d.unit_price===9000)).toBe(true);await customer.p.goto(base+'/travel/products/'+f.id);await expect(customer.p.getByTestId('product-title')).toContainText(detail.body.data.title);await expect(customer.p.getByTestId('departure-option').filter({hasText:'마감'})).toBeDisabled();await expect(customer.p.getByTestId('itinerary')).toContainText('합성 첫날');await shot(customer.p,customer.m,'departure-final-customer');return {product:f.id,departure:id,nativeContinuation:!existing,fromPrice:13000,soldoutUnit:9000,soldoutDisabled:true};},'departure-final');await c.close();await customer.c.close();}
await finishTokens(await browser.newPage());flush('departure-final');await browser.close();process.exitCode=results.some(r=>r.status==='FAIL')?1:0;
