// Independent fixed1052 native multi-item/status fixture and settled geometry/navigation.
// Fixtures created with customer UI, admin transitions with native UI. SQL NOT_RUN.
import fs from 'node:fs';import {out,base,travel,context,login,browser,api,expect,owned,step,flush,shot,finishTokens,results,run,syntheticPhone,inquiryBudgetWait} from './common.mjs';
const fixtures=JSON.parse(fs.readFileSync(out+'/admin.json')).owned.products;
const own=await context(390,'member'),admin=await context(390,'admin');await login(own.p,'member');await login(admin.p,'admin');
for(const status of ['CANCELLED','DECLINED','TEST_ACCEPTED','UNDER_REVIEW','TEST_INQUIRY'])await step(390,'native multiitem realistic title fixture '+status,async()=>{
 const before=await api(own.p,travel+'/cart');expect(before.body.data.items).toHaveLength(0);
 for(const f of fixtures){await own.p.goto(base+'/travel/products/'+f.id);await own.p.getByTestId('departure-option').filter({hasNotText:'마감'}).first().click();const w=own.p.waitForResponse(r=>r.url().endsWith(travel+'/cart')&&r.request().method()==='POST');await own.p.getByTestId('add-to-cart').click();const response=await w;expect(response.status()).toBe(201);for(const item of (await response.json()).data.items)if(!owned.carts.some(x=>x.id===item.id))owned.carts.push({id:item.id,role:'member'});flush('mobile-final');}
 await own.p.getByTestId('go-cart').click();await expect(own.p.getByTestId('cart-item')).toHaveCount(2);await own.p.getByTestId('contact-name').fill(run+' contact geometry');await own.p.getByTestId('contact-phone').fill(syntheticPhone());await own.p.getByTestId('ack-test').check();const w=own.p.waitForResponse(r=>r.url().endsWith(travel+'/inquiries')&&r.request().method()==='POST');await inquiryBudgetWait();await own.p.getByTestId('submit-inquiry').click();const r=await w;expect(r.status()).toBe(201);const d=(await r.json()).data;owned.inquiries.push({id:d.id,role:'member'});flush('mobile-final');expect(d.items).toHaveLength(2);expect(Number(d.total_amount)).toBe(26000);await expect(own.p).toHaveURL(new RegExp('/travel/requests/'+d.id));
 if(['UNDER_REVIEW','TEST_ACCEPTED','DECLINED'].includes(status)){await admin.p.goto(base+'/admin/travel-lab/inquiries');const id=admin.p.getByText(d.reference??String(d.id),{exact:true}).first();await expect(id).toBeVisible();const row=id.locator('xpath=ancestor::*[.//button][1]');await row.getByRole('button').last().click();await admin.p.locator('.fixed.z-\\[9999\\]').getByText(/상세 보기|상세보기|보기/).last().click();await expect(admin.p).toHaveURL(new RegExp('/inquiries/'+d.id));await admin.p.locator('textarea').fill('Own independent synthetic geometry status');const labels=status==='TEST_ACCEPTED'?['검토 중','테스트 수락']:[status==='UNDER_REVIEW'?'검토 중':'진행 어려움'];for(const label of labels){await admin.p.getByRole('button',{name:label,exact:true}).click();const change=admin.p.waitForResponse(r=>r.url().endsWith(travel+'/admin/inquiries/'+d.id)&&r.request().method()==='PATCH');await admin.p.getByRole('button',{name:/저장/}).click();expect((await change).status()).toBe(200);}}
 if(status==='CANCELLED'){await own.p.getByTestId('cancel-request').click();await own.p.getByTestId('cancel-confirm').click();await expect(own.p.getByTestId('detail-status')).toContainText('취소');}
 const final=await api(own.p,travel+'/inquiries/'+d.id);expect(final.body.data.status).toBe(status);return {inquiryId:d.id,http:201,itemCount:2,status,amount:26000,fixtureMethod:'native UI (tap390), not API setup'};
},'mobile-final');
await own.c.close();await admin.c.close();
for(const width of [390,1440]){const {p,c,m}=await context(width,'member');await login(p,'member');let data;
 await step(width,'MOBILE-01 all cards descendants full text date amount bounds settledDOM',async()=>{
 const response=p.waitForResponse(r=>new URL(r.url()).pathname===travel+'/inquiries'&&r.request().method()==='GET');await p.goto(base+'/travel/requests');const r=await response;expect(r.status()).toBe(200);data=(await r.json()).data.data;await expect(p.getByTestId('request-card')).toHaveCount(data.length);await expect(p.getByTestId('inquiries-loading')).toHaveCount(0);await p.waitForLoadState('networkidle');await p.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
 const geometry=await p.evaluate(()=>{
  const rect=e=>{const r=e.getBoundingClientRect();return {left:r.left,right:r.right,top:r.top,bottom:r.bottom,width:r.width,height:r.height};};
  const cards=[...document.querySelectorAll('[data-testid=request-card]')].map(e=>{
   const descendants=[...e.querySelectorAll('*')].map(el=>({tag:el.tagName,bounds:rect(el),scrollWidth:el.scrollWidth,clientWidth:el.clientWidth,overflowX:getComputedStyle(el).overflowX,textOverflow:getComputedStyle(el).textOverflow,lineClamp:getComputedStyle(el).webkitLineClamp,fontSize:getComputedStyle(el).fontSize}));
   const title=e.querySelector(':scope > p');const header=e.querySelector(':scope > div');const date=header.querySelector(':scope > span');const status=e.querySelector('[data-testid=request-status]');
   const ancestors=[];for(let a=e;a;a=a.parentElement)ancestors.push({tag:a.tagName,overflowX:getComputedStyle(a).overflowX,scrollWidth:a.scrollWidth,clientWidth:a.clientWidth});
   const textRanges=[];const walk=document.createTreeWalker(e,NodeFilter.SHOW_TEXT);while(walk.nextNode()){const node=walk.currentNode;if(!node.textContent.trim())continue;const range=document.createRange();range.selectNodeContents(node);for(const r of range.getClientRects())textRanges.push({left:r.left,right:r.right,top:r.top,bottom:r.bottom,width:r.width,height:r.height});}
   return {bounds:rect(e),direction:getComputedStyle(e).flexDirection,text:e.textContent,title:title.textContent,date:date.textContent,status:status?.textContent,titleStyle:{overflowX:getComputedStyle(title).overflowX,textOverflow:getComputedStyle(title).textOverflow,lineClamp:getComputedStyle(title).webkitLineClamp,scrollHeight:title.scrollHeight,clientHeight:title.clientHeight},descendants,ancestors,textRanges};
  });return {viewport:innerWidth,configuredWidth:null,document:document.documentElement.scrollWidth,body:document.body.scrollWidth,cards};
 });geometry.configuredWidth=width;
 const statuses=new Set(data.map(d=>d.status));for(const value of ['TEST_INQUIRY','UNDER_REVIEW','TEST_ACCEPTED','DECLINED','CANCELLED'])expect(statuses.has(value)).toBe(true);
 expect(geometry.document).toBeLessThanOrEqual(width);expect(geometry.body).toBeLessThanOrEqual(width);expect(geometry.viewport).toBe(width);
 for(let i=0;i<data.length;i++){const d=data[i],card=geometry.cards[i],title=d.first_product_name??d.items?.[0]?.product_name?.ko??'';expect(card.bounds.left).toBeGreaterThanOrEqual(0);expect(card.bounds.right).toBeLessThanOrEqual(width);expect(card.direction).toBe('column');expect(card.text).toContain('요청 #'+d.id);expect(card.title).toBe(title);expect(card.date).toContain(String(d.created_at).slice(0,16));expect(card.status?.trim().length).toBeGreaterThan(0);expect(card.text.replaceAll(',','')).toContain(String(Number(d.total_amount)));expect(card.titleStyle.lineClamp).toBe('none');expect(card.titleStyle.scrollHeight).toBeLessThanOrEqual(card.titleStyle.clientHeight);for(const r of card.textRanges){expect(r.left).toBeGreaterThanOrEqual(card.bounds.left-1);expect(r.right).toBeLessThanOrEqual(card.bounds.right+1);}for(const e of card.descendants){expect(e.bounds.left).toBeGreaterThanOrEqual(card.bounds.left-1);expect(e.bounds.right).toBeLessThanOrEqual(card.bounds.right+1);expect(e.textOverflow).not.toBe('ellipsis');}expect(card.ancestors.some(e=>['hidden','clip'].includes(e.overflowX)&&e.scrollWidth>e.clientWidth)).toBe(false);}
 await shot(p,m,'mobile-final-list');return {http:200,cardCount:data.length,serverRows:data.map(d=>({id:d.id,status:d.status,createdAt:d.created_at,itemCount:d.items?.length,title:d.first_product_name,amount:d.total_amount})),geometry};
 },'mobile-final');
 await step(width,'native Enter exact detail route then actual tap/click',async()=>{expect(data?.length).toBeGreaterThan(0);const id=data[0].id;await p.getByTestId('request-card').first().focus();await p.keyboard.press('Enter');await expect(p).toHaveURL(new RegExp('/travel/requests/'+id+'(?:\\?|$)'));await expect(p.getByTestId('detail-status')).toBeVisible();await shot(p,m,'mobile-final-enter-detail');const w=p.waitForResponse(r=>new URL(r.url()).pathname===travel+'/inquiries');await p.goto(base+'/travel/requests');expect((await w).status()).toBe(200);await expect(p.getByTestId('request-card')).toHaveCount(data.length);if(width===390)await p.getByTestId('request-card').first().tap();else await p.getByTestId('request-card').first().click();await expect(p).toHaveURL(new RegExp('/travel/requests/'+id+'(?:\\?|$)'));await expect(p.getByTestId('detail-status')).toBeVisible();return {id,keyboard:'Enter',pointer:width===390?'tap':'mouse click'};},'mobile-final');await c.close();}
await finishTokens(await browser.newPage());flush('mobile-final');await browser.close();process.exitCode=results.some(r=>r.status==='FAIL')?1:0;
