import {a,base,out,travel,run,context,login,browser,expect,shot,api,step,owned,cleanup,flush,results,scrub,finishTokens} from './common.mjs';import fs from 'node:fs';
const commerce='/api/modules/sirsoft-ecommerce/admin';const reused=process.env.W04_REUSE_CATEGORIES?JSON.parse(fs.readFileSync(out+'/admin-tag-placeholder-harness.json')):null;
for(const width of [390,1440]){
 const {p,c,m}=await context(width,'admin');await login(p,'admin');let policy,product,category,categoryTitle;
 if(process.env.W04_ADMIN_MODE!=='product')await step(width,'native UI own explicit KR FREE shipping policy create',async()=>{
 await p.goto(base+'/admin/ecommerce/shipping-policies/create');await p.locator('input[name="name[ko]"]').fill(run+' FREE '+width);await p.getByRole('button',{name:'국가를 선택하세요',exact:true}).click();await p.getByRole('option',{name:'대한민국 (KR)',exact:true}).click();await p.getByRole('button',{name:/국가 추가/}).click();await p.getByRole('button',{name:'고정배송비',exact:true}).click();await p.getByRole('option',{name:'무료배송',exact:true}).click();
 await p.locator('input[name=is_active]').check();await p.locator('input[name=is_default]').uncheck();await shot(p,m,'own-policy-form');const w=p.waitForResponse(r=>r.url().includes(commerce+'/shipping-policies')&&r.request().method()==='POST');await p.locator('#footer_save_button').click();const r=await w;const body=await r.json();if(r.status()!==201)console.log('policy reject',r.status(),scrub(JSON.stringify({errors:body.errors,message:body.message})));expect(r.status()).toBe(201);const d=body.data;policy=d.id;owned.policies.push({id:policy});flush('admin');const q=await api(p,commerce+'/shipping-policies/'+policy,'GET',undefined,'admin');expect(q.body.data.country_settings.some(x=>x.country_code==='KR'&&x.charge_policy==='free')).toBe(true);return {id:policy,http:201,country:'KR',charge_policy:'free'};
 },'admin');
 if(!policy){results.push({width,name:'critical admin journey',status:'BLOCKED',reason:'Owned native KR/FREE policy UI creation failed; no shared policy fallback'});flush('admin');await c.close();continue;}
 if(policy){await step(width,'own category bounded native API setup',async()=>{if(reused){category=reused.results.find(r=>r.width===width&&r.name==='own category bounded native API setup').detail.id;const q=await api(p,commerce+'/categories/'+category,'GET',undefined,'admin');expect(q.status).toBe(200);categoryTitle=q.body.data.name.ko;owned.categories.push({id:category});return {id:category,setup:'reuse own earlier bounded fixture'};}const q=await api(p,commerce+'/categories','POST',{name:{ko:run+' 합성 '+width,en:run+' Synthetic '+width},slug:run.toLowerCase()+width,is_active:true},'admin');expect(q.status).toBe(201);category=q.body.data.id;categoryTitle=run+' 합성 '+width;owned.categories.push({id:category});flush('admin');return {id:category,http:201};},'admin');
 await step(width,'native UI own product and options create',async()=>{
 await p.goto(base+'/admin/ecommerce/products/create');await p.waitForLoadState('networkidle');await p.locator('input[name=product_code]').first().fill(run+'P'+width);await p.locator('input[name="name[ko]"]').fill('제주 '+run+' 합성 '+width);
 const cat=p.locator(width===390?'.category-item-mobile':'.category-item').filter({hasText:categoryTitle});await cat.click();await p.getByRole('button',{name:/선택한 카테고리 추가/}).click();
 await p.locator('input[name=list_price]:visible').fill('20000');await p.locator('input[name=selling_price]:visible').fill('12000');await p.locator('input[name=selling_price]:visible').blur();await p.waitForTimeout(500);await p.getByRole('button',{name:/비과세/,exact:true}).click();await p.getByRole('button',{name:'판매중',exact:true}).click();await p.getByRole('button',{name:'전시중',exact:true}).click();
 await p.getByRole('button',{name:/옵션그룹 추가/}).click();await p.locator('input[name="option_input_name_0[ko]"]').fill('출발');await p.waitForTimeout(400);await p.locator('input[placeholder="옵션값을 쉼표(,)로 구분하여 입력"]').fill('합성 A');await p.locator('input[placeholder="옵션값을 쉼표(,)로 구분하여 입력"]').press('Enter');await expect(p.getByRole('dialog')).toBeVisible();await p.getByRole('dialog').locator('input[type=text]').nth(0).fill('합성 A');await p.getByRole('dialog').locator('input[type=text]').nth(1).fill('Synthetic A');await p.getByRole('dialog').getByRole('button',{name:/추가/,exact:true}).click();await expect(p.getByRole('dialog')).toHaveCount(0);await p.locator('input[class*=min-w-][placeholder=""]').fill('합성 B');await p.locator('input[class*=min-w-][placeholder=""]').press('Enter');await expect(p.getByRole('dialog')).toBeVisible();await p.getByRole('dialog').locator('input[type=text]').nth(0).fill('합성 B');await p.getByRole('dialog').locator('input[type=text]').nth(1).fill('Synthetic B');await p.getByRole('dialog').getByRole('button',{name:/추가/,exact:true}).click();await p.getByRole('button',{name:/옵션 생성/,exact:true}).click();await p.waitForTimeout(500);await shot(p,m,'product-after-options');
 await expect(p.locator(width===390?'#option_table_mobile':'#option_table_desktop')).toBeVisible();
 const opts=p.locator(width===390?'#option_table_mobile':'#option_table_desktop').locator('input[type=number]:visible');console.log('option visible number count',width,await opts.count());
 await opts.nth(0).fill('20000');await opts.nth(1).fill('12000');await opts.nth(2).fill('5');await opts.nth(2).blur();await opts.nth(7).fill('20000');await opts.nth(8).fill('10000');await opts.nth(9).fill('5');await opts.nth(9).blur();await p.waitForTimeout(500);await p.locator('input[name=product_code]:visible').first().fill(run+'P'+width);await p.locator('input[name=list_price]:visible').fill('20000');await p.locator('input[name=selling_price]:visible').fill('12000');await p.locator('input[name=selling_price]:visible').blur();await p.waitForTimeout(500);
 await p.getByRole('switch',{name:'use_default_shipping',exact:true}).click();await p.getByRole('button',{name:run+' FREE '+width,exact:true}).click();await shot(p,m,'native-product-form');
 const wait=p.waitForResponse(r=>r.url().endsWith(commerce+'/products')&&r.request().method()==='POST');await p.getByTestId('product-save').click();const r=await wait;const d=await r.json();if(r.status()!==201)console.log('product create rejected',r.status(),scrub(JSON.stringify({errors:d.errors,message:d.message})));expect(r.status()).toBe(201);product=d.data.id;owned.products.push({id:product,policy,category});flush('admin');return {id:product,http:201};
 },'admin');}
 if(!product){results.push({width,name:'travel registration departure customer discover cart',status:'BLOCKED',reason:'Native UI product/policy creation did not complete; API-only substitution forbidden'});flush('admin');}
 await c.close();
}
await finishTokens(await browser.newPage());await browser.close();flush('admin');process.exitCode=results.some(r=>r.status==='FAIL')?1:0;
