import fs from 'node:fs';import crypto from 'node:crypto';import path from 'node:path';import {execFileSync} from 'node:child_process';import {chromium,expect as originalExpect} from '@playwright/test';
export const expect=originalExpect.configure({timeout:15000});export const SHA='598a89fff702d51c1405f1a5952d95ab1d2651f4',out='docs/symphony/evidence/W04_BROWSER_RECHECK',travel='/api/modules/raonslab-travel_lab';
const file='/home/ubuntu/.agentopt-v2/workspaces/req_81ac33cac94046b9a2249cd14c0d00ba/storage/framework/testing/travel-live-review-b06dba2b91ea/access.json';
if(fs.lstatSync(file).isSymbolicLink()||(fs.statSync(file).mode&0o077)||(fs.statSync(path.dirname(file)).mode&0o077))throw Error('Private scoped access required');
export const a=JSON.parse(fs.readFileSync(file));if(a.source_sha!==SHA||a.db!=='req81_travel_lab'||Date.parse(a.expires_at)<=Date.now()||a.base_url!=='http://127.0.0.1:18871')throw Error('Access binding/expiry mismatch');
export const actualHead=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim();
execFileSync('git',['merge-base','--is-ancestor',SHA,actualHead]);
const changes=execFileSync('git',['diff','--name-only',SHA],{encoding:'utf8'}).trim().split('\n').filter(Boolean);if(changes.some(p=>!p.startsWith('tests/W04_RECHECK/')&&!p.startsWith(out+'/')&&p!=='docs/symphony/W04_BROWSER_RECHECK.md'))throw Error('Product revision mismatch');
const issued=[];
export const base=a.base_url,run='W04R'+Date.now(),results=[],metrics=[],owned={inquiries:[],carts:[],products:[],posts:[],policies:[],categories:[]};fs.mkdirSync(out,{recursive:true});
// 실제 연락처를 코드에 고정하지 않고 테스트 프로세스 안에서만 합성한다.
export const syntheticPhone=(edited=false)=>[String(0).repeat(3),String(0).repeat(4),String(0).repeat(3)+(edited?'1':'0')].join('-');
export const hash=x=>crypto.createHash('sha256').update(typeof x==='string'||Buffer.isBuffer(x)?x:JSON.stringify(x)).digest('hex');
export function scrub(s){s=String(s).replace(/\u001b\[[0-9;]*m/g,'');for(const r of ['member','other_member','admin'])for(const v of Object.values(a[r]))if(typeof v==='string')s=s.replaceAll(v,'[private]');return s.replace(/W04R.*?contact[^\"\n]*/g,'[synthetic contact]').replace(/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}/gi,'[private uuid]').replace(/Bearer\s+\S+/gi,'Bearer [private]').replace(/[\w.+-]+@[\w.-]+\.[\w-]+/g,'[private email]').replace(/000-0000-000[01]/g,'[synthetic contact]');}
export function flush(name){fs.writeFileSync(out+'/'+name+'.json',scrub(JSON.stringify({tested_sha:SHA,actual_head:actualHead,run,elapsed_seconds:(Date.now()-Number(run.slice(4)))/1000,results,metrics,owned},null,2))+'\n');}
export async function step(width,name,fn,file='journey'){try{const detail=await fn();results.push({width,name,status:['PASS','FAIL','NOT_RUN','BLOCKED'].includes(detail?.status)?detail.status:'PASS',detail});console.log(width,name,results.at(-1).status);return results.at(-1).status==='PASS';}catch(e){results.push({width,name,status:'FAIL',error:scrub(e.message).slice(0,1600)});console.log(width,name,'FAIL',scrub(e.message).split('\n')[0]);return false;}finally{flush(file);}}
export const browser=await chromium.launch();
export async function context(width,role='guest'){const c=await browser.newContext({locale:'ko-KR',viewport:{width,height:1000},hasTouch:width===390}),p=await c.newPage();p.setDefaultTimeout(12000);const originalWait=p.waitForResponse.bind(p);p.waitForResponse=(...args)=>{const promise=originalWait(...args);promise.catch(()=>{});return promise;};const m={width,role,pageErrors:[],consoleErrors:[],requests:[],httpErrors:[],overflow:[]};metrics.push(m);p.on('pageerror',e=>m.pageErrors.push(scrub(e.message)));p.on('console',e=>{if(e.type()==='error')m.consoleErrors.push(scrub(e.text()).slice(0,1600));});p.on('request',r=>{const pathname=new URL(r.url()).pathname;if(pathname.startsWith('/api/'))m.requests.push({path:pathname,method:r.method(),nativeBearer:!!r.headers().authorization?.startsWith('Bearer ')});});p.on('response',r=>{if(r.status()>=400)m.httpErrors.push({path:new URL(r.url()).pathname,status:r.status()});});return {p,c,m};}
export async function login(p,role){await p.goto(base+'/login');await p.locator('#travel-login-email').fill(a[role].email);await p.locator('#travel-login-password').fill(a[role].password);const wait=p.waitForResponse(r=>new URL(r.url()).pathname==='/api/auth/login'&&r.request().method()==='POST');if(p.viewportSize().width===390)await p.locator('form button[type=submit]').tap();else await p.locator('form button[type=submit]').click();const response=await wait;expect(response.status()).toBe(200);const body=await response.json();const token=body.data?.token||body.data?.access_token;if(token){issued.push(token);const tf='storage/framework/testing/w04-private/issued.json';const prev=fs.existsSync(tf)?JSON.parse(fs.readFileSync(tf)):[];prev.push({token,role});fs.writeFileSync(tf,JSON.stringify(prev),{mode:0o600});}await expect(p).not.toHaveURL(/\/login/);}
export async function shot(p,m,name){await p.screenshot({path:out+'/'+name+'-'+m.width+'.png',fullPage:true,mask:[p.locator('input,textarea'),p.getByText(/@/),p.getByText(/000-0000/),p.getByText(/Synthetic recovery|Synthetic verifier|W04R.*contact/),p.getByText(/[a-f0-9]{8}-[a-f0-9]{4}-/i)]});const o=await p.evaluate(()=>({viewport:innerWidth,document:document.documentElement.scrollWidth}));m.overflow.push({name,...o});if(o.document>m.width)results.push({width:m.width,name:'horizontal overflow '+name,status:'FAIL',detail:o});}
export async function api(p,path,method='GET',data,role='member'){const r=await p.request.fetch(base+path,{method,headers:{Accept:'application/json',Authorization:'Bearer '+a[role].bearer_token},...(data!==undefined?{data}:{})});return {status:r.status(),body:await r.json()};}
export async function cleanup(p){for(const f of owned.inquiries){const q=await api(p,travel+'/inquiries/'+f.id,'GET',undefined,f.role);if(!['CANCELLED','DECLINED'].includes(q.body.data?.status))await api(p,travel+'/inquiries/'+f.id+'/cancel','POST',{},f.role);const r=await api(p,travel+'/inquiries/'+f.id,'GET',undefined,f.role);results.push({name:'cleanup own inquiry',status:['CANCELLED','DECLINED'].includes(r.body.data?.status)?'PASS':'FAIL',id:f.id,terminalState:r.body.data?.status});}for(const f of owned.carts){const r=await api(p,travel+'/cart','GET',undefined,f.role);if(r.body.data?.items.some(x=>x.id===f.id))await api(p,travel+'/cart/'+f.id,'DELETE',undefined,f.role);}for(const f of owned.posts){const r=await api(p,'/api/modules/sirsoft-board/admin/board/'+f.slug+'/posts/'+f.id,'DELETE',undefined,'admin');const q=await api(p,'/api/modules/sirsoft-board/admin/board/'+f.slug+'/posts/'+f.id,'GET',undefined,'admin');results.push({name:'cleanup own support post',id:f.id,status:r.status===200&&!!q.body.data?.deleted_at?'PASS':'FAIL',http:r.status,requery:q.status});}}

export async function finishTokens(p){for(const token of issued){const r=await p.request.post(base+'/api/auth/logout',{headers:{Accept:'application/json',Authorization:'Bearer '+token},data:{}});results.push({name:'delete own issued token via native logout',status:[200,401].includes(r.status())?'PASS':'FAIL',http:r.status()});}flush('issued-token-cleanup');}
export async function logout(p,width){if(width===390)await p.getByTestId('menu-toggle').click();const w=p.waitForResponse(r=>r.url().endsWith('/api/auth/logout'));await p.getByRole('button',{name:'로그아웃',exact:true}).click();expect((await w).status()).toBe(200);await expect(p).toHaveURL(/\/login/);}
