import fs from 'node:fs';import {out,base,travel,context,login,browser,api,expect,owned,results,step,cleanup,flush,shot,finishTokens,SHA} from './common.mjs';
const ledger=fs.readdirSync(out).filter(n=>n.endsWith('.json')).map(n=>{try{return JSON.parse(fs.readFileSync(out+'/'+n));}catch{return null;}}).filter(x=>x?.tested_sha===SHA&&x.owned);
for(const key of Object.keys(owned)){owned[key]=ledger.flatMap(x=>x.owned[key]??[]).filter((f,i,arr)=>arr.findIndex(x=>x.id===f.id&&x.role===f.role&&x.slug===f.slug)===i);}
const p=await browser.newPage();const ownProductIds=owned.products.map(f=>f.id);
// Reconcile early cart harness rows by fresh native owner GET plus known self-created product IDs.
for(const role of ['member','other_member']){const q=await api(p,travel+'/cart','GET',undefined,role);for(const item of q.body.data.items)if(ownProductIds.includes(item.product_id)&&!owned.carts.some(f=>f.id===item.id&&f.role===role))owned.carts.push({id:item.id,role,provenance:'Actual fresh-owner cart GET and this Request known own product identity'});}
await cleanup(p);flush('cleanup');
for(const f of owned.products){await step(0,'own product departure inactive reserved zero unpublish '+f.id,async()=>{const q=await api(p,travel+'/admin/catalog/'+f.id,'GET',undefined,'admin');expect(q.status).toBe(200);for(const d of q.body.data.departures){expect(d.reserved).toBe(0);const r=await api(p,travel+'/admin/catalog/'+f.id+'/departures/'+d.id,'PUT',{product_option_id:d.product_option_id,departure_date:d.departure_date,return_date:d.return_date,capacity:d.capacity,is_active:false},'admin');expect(r.status).toBe(200);}const r=await api(p,travel+'/admin/catalog/'+f.id,'PATCH',{published:false},'admin');expect(r.status).toBe(200);const re=await api(p,travel+'/admin/catalog/'+f.id,'GET',undefined,'admin');expect(re.body.data.published).toBe(false);expect(re.body.data.departures.every(d=>d.reserved===0&&d.is_active===false)).toBe(true);return {productId:f.id,departures:re.body.data.departures.map(d=>({id:d.id,reserved:d.reserved,active:d.is_active})),published:false};},'cleanup');}
// Exactly own IDs: API-only pagination fixture cleanup stays distinguished from UI lifecycle.
const bulk=await api(p,'/api/modules/sirsoft-ecommerce/admin/products/bulk-update','PATCH',{ids:ownProductIds,bulk_changes:{display_status:'hidden'}},'admin');results.push({name:'native API bounded own-products hidden',status:bulk.status===200?'PASS':'FAIL',http:bulk.status,ids:ownProductIds});
for(const f of owned.products){const q=await api(p,'/api/modules/sirsoft-ecommerce/admin/products/'+f.id,'GET',undefined,'admin');const pub=await api(p,travel+'/catalog/'+f.id);results.push({name:'actual own product final requery',id:f.id,status:q.body.data?.display_status==='hidden'&&pub.status===404?'PASS':'FAIL',display:q.body.data?.display_status,public:pub.status});}
for(const f of owned.policies){const q=await api(p,'/api/modules/sirsoft-ecommerce/admin/shipping-policies/'+f.id,'GET',undefined,'admin');if(q.body.data?.is_active)await api(p,'/api/modules/sirsoft-ecommerce/admin/shipping-policies/'+f.id+'/toggle-active','PATCH',{},'admin');const re=await api(p,'/api/modules/sirsoft-ecommerce/admin/shipping-policies/'+f.id,'GET',undefined,'admin');results.push({name:'actual own policy inactive requery',id:f.id,status:re.body.data?.is_active===false?'PASS':'FAIL'});}
for(const f of owned.categories){const q=await api(p,'/api/modules/sirsoft-ecommerce/admin/categories/'+f.id,'GET',undefined,'admin');const d=q.body.data;if(d?.is_active)await api(p,'/api/modules/sirsoft-ecommerce/admin/categories/'+f.id,'PUT',{name:d.name,slug:d.slug,is_active:false,parent_id:d.parent_id},'admin');const re=await api(p,'/api/modules/sirsoft-ecommerce/admin/categories/'+f.id,'GET',undefined,'admin');results.push({name:'actual own category inactive requery',id:f.id,status:re.body.data?.is_active===false?'PASS':'FAIL'});}
for(const f of owned.posts){const q=await api(p,'/api/modules/sirsoft-board/admin/board/'+f.slug+'/posts/'+f.id,'GET',undefined,'admin');let own404;if(f.slug==='travel-lab-questions')own404=(await api(p,travel+'/support/questions/'+f.id)).status;results.push({name:'actual own support final requery',id:f.id,slug:f.slug,status:!!q.body.data?.deleted_at&&(own404===undefined||own404===404)?'PASS':'FAIL',deleted:!!q.body.data?.deleted_at,ownerHttp:own404});}
for(const role of ['member','other_member']){const q=await api(p,travel+'/cart','GET',undefined,role);results.push({name:'actual final actor cart empty',role,status:q.body.data.items.length===0?'PASS':'FAIL',count:q.body.data.items.length});}
// Read only privately recorded native-login tokens issued by this test process family.
const tokenFile='storage/framework/testing/w04-private/issued.json';let tokenCount=0;if(fs.existsSync(tokenFile)){const issued=JSON.parse(fs.readFileSync(tokenFile));for(const f of issued){await p.request.post(base+'/api/auth/logout',{headers:{Accept:'application/json',Authorization:'Bearer '+f.token},data:{}});const q=await p.request.get(base+'/api/auth/user',{headers:{Accept:'application/json',Authorization:'Bearer '+f.token}});results.push({name:'actual recorded own-issued token revoked requery',status:q.status()===401?'PASS':'FAIL',http:q.status()});tokenCount++;}fs.unlinkSync(tokenFile);}
results.push({name:'early interrupted own support browser login tokens',status:'BLOCKED',reason:'Six native login responses occurred before durable private token ledger existed; Chromium closed before cleanup. Those token values/IDs were not retained. Native API exposes no scoped token enumeration. Provisioned actor tokens and unrelated tokens preserved; no logout-all-devices or broad token deletion.'});
const statuses=[];for(const f of owned.inquiries){const q=await api(p,travel+'/inquiries/'+f.id,'GET',undefined,f.role);statuses.push({id:f.id,status:q.body.data?.status});}
fs.writeFileSync(out+'/cleanup-counts.json',JSON.stringify({sourceSHA:SHA,counts:Object.fromEntries(Object.entries(owned).map(([k,v])=>[k,v.length])),inquiryStatuses:statuses,recordedIssuedTokensRequeried:tokenCount,earlyUnrecordedIssuedTokens:'BLOCKED: six',allRequestsCancelled:statuses.every(x=>x.status==='CANCELLED'),nativeDeclinedTerminalLimitation:'DECLINED cannot become CANCELLED; two intentional decline fixtures are closed, reserved0 independently queried, cancel returns409.'},null,2)+'\n');flush('cleanup');await browser.close();process.exitCode=results.some(r=>r.status==='FAIL')?1:0;
