import fs from 'node:fs';import {syntheticPhone,run as contactRun} from './common.mjs';
import {a,base,out,travel,run,context,login,browser,expect,shot,api,step,owned,cleanup,flush,results,finishTokens,logout} from './common.mjs';
for(const width of [390,1440]){
 const {p,c,m}=await context(width,'member'),adm=await context(width,'admin');await login(p,'member');await login(adm.p,'admin');let id;const f=JSON.parse(fs.readFileSync(out+'/admin.json')).owned.products[width===390?0:1];
 await step(width,'date people native cart price ordinary inquiry201',async()=>{await p.goto(base+'/travel/products/'+f.id);await p.getByTestId('departure-option').filter({hasNotText:'마감'}).first().click();await p.getByTestId('people-increase').click();const add=p.waitForResponse(r=>r.url().endsWith(travel+'/cart')&&r.request().method()==='POST');await p.getByTestId('add-to-cart').click();const rr=await add;expect(rr.status()).toBe(201);const item=(await rr.json()).data.items[0];owned.carts.push({id:item.id,role:'member'});expect(item.quantity).toBe(2);await p.getByTestId('go-cart').click();await expect(p.getByTestId('cart-qty')).toContainText('2명');const cartId=item.id;const up=p.waitForResponse(r=>r.url().endsWith(travel+'/cart/'+cartId)&&r.request().method()==='PATCH');await p.getByTestId('cart-qty-increase').click();expect((await up).status()).toBe(200);await expect(p.getByTestId('cart-qty')).toContainText('3명');const down=p.waitForResponse(r=>r.url().endsWith(travel+'/cart/'+cartId)&&r.request().method()==='PATCH');await p.getByTestId('cart-qty-decrease').click();expect((await down).status()).toBe(200);await expect(p.getByTestId('cart-qty')).toContainText('2명');await p.getByTestId('cart-remove').click();await expect(p.getByRole('dialog')).toBeVisible();await shot(p,m,'cart-remove-dialog');await p.getByRole('dialog').getByRole('button',{name:/취소/}).click();await expect(p.getByTestId('submit-inquiry')).toBeDisabled();await p.getByTestId('contact-name').fill(run+' contact ordinary');await p.getByTestId('contact-phone').fill(syntheticPhone());await p.getByTestId('ack-test').check();const submit=p.waitForResponse(r=>r.url().endsWith(travel+'/inquiries')&&r.request().method()==='POST');await p.getByTestId('submit-inquiry').click();const r=await submit;expect(r.status()).toBe(201);const d=(await r.json()).data;id=d.id;owned.inquiries.push({id,role:'member'});expect(r.request().postDataJSON()).not.toHaveProperty('price');expect(r.request().postDataJSON()).not.toHaveProperty('total');expect(d.status).toBe('TEST_INQUIRY');expect(Number(d.total_amount)).toBe(26000);expect(d.items[0].unit_price).toBeTruthy();expect(Number(d.items[0].unit_price)).toBe(13000);await expect(p).toHaveURL(new RegExp('/travel/requests/'+id));await expect(p.getByTestId('detail-status')).toContainText('테스트 접수');await shot(p,m,'ordinary-inquiry');return {id,cartQuantity:item.quantity,http:201,status:d.status,serverTotal:Number(d.total_amount),serverUnitPrice:Number(d.items[0].unit_price),priceNotSent:true};});
 if(id){await step(width,'my requests native admin review note test accepted',async()=>{await p.goto(base+'/travel/requests');await expect(p.getByText('요청 #'+id,{exact:false}).first()).toBeVisible({timeout:15000});await shot(p,m,'my-requests');await adm.p.goto(base+'/admin/travel-lab/inquiries/'+id);await adm.p.locator('textarea').fill(run+' synthetic admin note');for(const label of ['검토 중','테스트 수락']){await adm.p.getByRole('button',{name:label,exact:true}).click();const wait=adm.p.waitForResponse(r=>r.url().endsWith(travel+'/admin/inquiries/'+id)&&r.request().method()==='PATCH');await adm.p.getByRole('button',{name:/저장/}).click();const r=await wait;expect(r.status()).toBe(200);if(label==='테스트 수락')expect((await r.json()).data.status).toBe('TEST_ACCEPTED');}await shot(adm.p,adm.m,'admin-accepted');return {id,status:'TEST_ACCEPTED'};});
 await step(width,'customer native logout relogin accepted status cancel modal',async()=>{await p.goto(base+'/travel/requests/'+id);if(width===390)await p.getByTestId('menu-toggle').click();const wait=p.waitForResponse(r=>r.url().endsWith('/api/auth/logout'));await p.getByRole('button',{name:'로그아웃',exact:true}).click();expect((await wait).status()).toBe(200);await expect(p).toHaveURL(/\/login/);await login(p,'member');await p.goto(base+'/travel/requests/'+id);await expect(p.getByTestId('detail-status')).toContainText('테스트 수락',{timeout:15000});await expect(p.getByText(/실제 예약·결제/).first()).toBeVisible();await shot(p,m,'relogin-accepted');await p.getByTestId('cancel-request').click();await expect(p.getByRole('dialog')).toBeVisible();await shot(p,m,'cancel-ordinary');await p.getByTestId('cancel-confirm').click();await expect(p.getByTestId('detail-status')).toContainText('취소');return {id};});}
 await c.close();await adm.c.close();
}
const p=await browser.newPage();await cleanup(p);flush('journey');await finishTokens(await browser.newPage());await browser.close();process.exitCode=results.some(r=>r.status==='FAIL')?1:0;
