/** Independent read-only W04 browser verification. No authentication, mutations, mocks,
 * or credential access. Only the explicitly named loading/retry scenarios inject a fault.
 * Run: node tests/W04_RECHECK/public-recheck.mjs
 */
const {chromium,expect}=await import(process.env.W04_PLAYWRIGHT_MODULE || '@playwright/test');
import crypto from 'node:crypto';
import { mkdir, writeFile } from 'node:fs/promises';
import { execFileSync } from 'node:child_process';
const target = '598a89fff702d51c1405f1a5952d95ab1d2651f4';
const head = execFileSync('git', ['rev-parse', 'HEAD'], { encoding:'utf8' }).trim();
{ const changes=execFileSync('git',['diff','--name-only',target],{encoding:'utf8'}).trim().split('\n').filter(Boolean); if(changes.some(p=>!(p.startsWith('tests/W04_RECHECK/')||p.startsWith('docs/symphony/evidence/W04_BROWSER_RECHECK/')||p==='docs/symphony/W04_BROWSER_RECHECK.md'))) throw new Error('Product source differs from fixed target'); }
if(head!==target)throw new Error('HEAD is not exact review target');
const tree = execFileSync('git', ['rev-parse', 'HEAD^{tree}'], { encoding:'utf8' }).trim();
if(tree!=='9e00273bdf18d6a713343755aac54f44a9b032b4')throw new Error('Tree mismatch');
const base = process.env.W04_BASE_URL || 'http://127.0.0.1:18871';
const dir = 'docs/symphony/evidence/W04_BROWSER_RECHECK';
await mkdir(dir, {recursive:true});
const report = {target, actualHead:head, tree, base, started:new Date().toISOString(), browser:'Chromium', authentication:'guest', mutations:0, scenarios:[], viewports:[], limitations:[]};
const browser = await chromium.launch({headless:true});
for (const width of [390,1440]) {
 const context = await browser.newContext({viewport:{width,height:width===390?844:1000},locale:'ko-KR',hasTouch:width===390,isMobile:width===390});
 const page = await context.newPage(); page.setDefaultTimeout(15000);
 const pointer=async locator=>width===390?locator.tap():locator.click();
 const assetWork=[];const assets=[];page.on('response',r=>{if(/\.(js|css)(?:$|\?)/.test(r.url()))assetWork.push(r.body().then(b=>assets.push({path:new URL(r.url()).pathname,status:r.status(),sha256:crypto.createHash('sha256').update(b).digest('hex'),bytes:b.length})).catch(()=>{}));});
 const events = {width,pageErrors:[],consoleErrors:[],consoleWarnings:[], failedRequests:[],httpErrors:[],overflows:[]};
 page.on('pageerror',e=>events.pageErrors.push(e.message));
 page.on('console',m=>{if(m.type()==='error')events.consoleErrors.push(m.text());if(m.type()==='warning')events.consoleWarnings.push(m.text());});
 page.on('requestfailed',r=>events.failedRequests.push({path:new URL(r.url()).pathname,error:r.failure()?.errorText}));
 page.on('response',r=>{if(r.status()>=400)events.httpErrors.push({path:new URL(r.url()).pathname,status:r.status()});});
 const test = async (name,fn)=>{if(process.env.W04_ONLY && !process.env.W04_ONLY.split(',').includes(name))return;const record={width,name};try{const detail=await fn();record.status=detail?.status||'PASS';record.detail=detail;}catch(e){record.status='FAIL';record.error=e.message.replace(/\u001b\[[0-9;]*m/g,'').slice(0,3000);await page.screenshot({path:`${dir}/public-failure-${name}-${width}.png`,fullPage:true}).catch(()=>{});}report.scenarios.push(record);console.log(`${width} ${name}: ${record.status}`);};
 const screenshot=async name=>{await page.screenshot({path:`${dir}/public-${name}-${width}.png`,fullPage:true});};
 const overflow=async name=>{const data=await page.evaluate(()=>({viewport:innerWidth,document:document.documentElement.scrollWidth,body:document.body.scrollWidth}));events.overflows.push({name,...data});expect(data.document).toBeLessThanOrEqual(width);expect(data.body).toBeLessThanOrEqual(width);};
 const catalog=async()=>{await expect(page.getByTestId('catalog-loading')).toHaveCount(0);await expect(page.getByTestId('catalog-results')).toBeVisible();};
 const go=async path=>{await page.goto(base+path);};
 const filters=async()=>{if(width===390 && !await page.getByTestId('search-filters').isVisible()) await pointer(page.getByTestId('filters-toggle'));await expect(page.getByTestId('search-filters')).toBeVisible();};
 const select=async(id,text)=>{await pointer(page.getByTestId(id));await pointer(page.getByRole('option',{name:text,exact:true}));};
 const catalogAction=async(fn,expected={})=>{const response=page.waitForResponse(r=>r.url().includes('/raonslab-travel_lab/catalog?')&&r.request().method()==='GET'&&Object.entries(expected).every(([k,v])=>new URL(r.url()).searchParams.get(k)===v));await fn();const r=await response;expect(r.status()).toBe(200);const json=await r.json();if(json.data.data.length)await catalog();else await expect(page.getByTestId('catalog-empty')).toBeVisible();const titles=await page.getByTestId('trip-card').evaluateAll(es=>es.map(e=>e.getAttribute('aria-label')));await expect.poll(async()=>await page.getByTestId('trip-card').evaluateAll(es=>es.map(e=>e.getAttribute('aria-label'))), {timeout:15000}).toEqual(json.data.data.map(x=>x.title));return json.data;};
 await test('home-real-facets-ko-layout',async()=>{await go('/');await expect(page.getByTestId('region-chip')).toHaveCount(4);await expect(page.getByTestId('theme-card')).toHaveCount(4);await expect(page.getByTestId('featured_trips-loading')).toHaveCount(0);expect(await page.getByTestId('trip-card').count()).toBeGreaterThan(0);expect(await page.locator('body').innerText()).not.toMatch(/\b(jeju|gangwon|busan|seoul|nature|wellness)\b/);await overflow('home');await screenshot('home');return {regions:await page.getByTestId('region-chip').allTextContents(),themes:await page.getByTestId('theme-card').allTextContents()};});
 await test('category-click-real-results',async()=>{const data=await catalogAction(()=>pointer(page.getByTestId('region-chip').filter({hasText:'제주'})),{region:'jeju'});expect(new URL(page.url()).searchParams.get('region')).toBe('jeju');expect(data.data.every(x=>x.region==='jeju')).toBe(true);expect(data.data.length).toBeGreaterThan(0);await overflow('category');return {count:data.data.length};});
 await test('theme-click-real-results',async()=>{await go('/');await page.getByTestId('theme-card').first().waitFor();const data=await catalogAction(()=>pointer(page.getByTestId('theme-card').filter({hasText:'자연'})),{theme:'nature'});expect(new URL(page.url()).searchParams.get('theme')).toBe('nature');expect(data.data.every(x=>x.theme==='nature')).toBe(true);return {count:data.data.length};});
 await test('hero-search-real-results',async()=>{await go('/');await page.getByTestId('hero-search-input').fill('제주');const data=await catalogAction(()=>pointer(page.getByTestId('hero-search-button')),{q:'제주'});expect(new URL(page.url()).searchParams.get('q')).toBe('제주');expect(data.data.length, 'Public catalog has two 제주 titles, but q=제주 returned no matches via real HTTP200').toBeGreaterThan(0);expect(data.data.every(x=>x.title.includes('제주'))).toBe(true);await screenshot('hero-search');return {count:data.data.length};});
 await test('combined-region-theme-date-price-filter',async()=>{await go('/travel/search');await catalog();await filters();await select('filter-region','제주');await select('filter-theme','자연');await page.getByTestId('filter-date_from').fill('2026-11-01');await page.getByTestId('filter-date_to').fill('2026-11-08');await page.getByTestId('filter-min_price').fill('180000');await page.getByTestId('filter-max_price').fill('210000');const data=await catalogAction(()=>pointer(page.getByTestId('filter-apply')),{region:'jeju',theme:'nature',date_from:'2026-11-01',max_price:'210000'});expect(data.data.length).toBeGreaterThan(0);expect(data.data[0].region).toBe('jeju');expect(data.data[0].theme).toBe('nature');await page.reload();await catalog();await filters();await expect(page.getByTestId('filter-date_to')).toHaveValue('2026-11-08');await expect(page.getByTestId('filter-max_price')).toHaveValue('210000');await overflow('filters');await screenshot('filters');return {query:new URL(page.url()).search, count:data.data.length};});
 await test('filter-reset',async()=>{await filters();const data=await catalogAction(()=>pointer(page.getByTestId('filter-reset')));expect(new URL(page.url()).search).toBe('');return {count:data.data.length};});
 for(const [label,value] of [['낮은 가격순','price_asc'],['높은 가격순','price_desc'],['출발 임박순','departure_asc'],['추천순','recommended']]) await test(`sort-${value}`,async()=>{const data=await catalogAction(()=>select('sort-select',label),{sort:value});expect(new URL(page.url()).searchParams.get('sort')).toBe(value);const prices=data.data.map(x=>x.from_price);if(value==='price_asc')expect(prices).toEqual([...prices].sort((a,b)=>a-b));if(value==='price_desc')expect(prices).toEqual([...prices].sort((a,b)=>b-a));if(value==='departure_asc'){const dates=data.data.map(x=>x.departures[0]?.departure_date);expect(dates).toEqual([...dates].sort());}await overflow('sort');return {order:data.data.map(x=>x.id)};});
 await test('pagination',async()=>{const ownIds=(process.env.W04_PAGINATION_IDS||'').split(',').filter(Boolean).map(Number);const q=process.env.W04_PAGINATION_Q;if(ownIds.length<13||!q)return {status:'NOT_RUN',reason:'Owned >12 published synthetic fixture IDs/query not supplied; only8 public items initially. API provisioning is never adminUIcreate PASS.'};
 const catalogResponse=(pageNo)=>page.waitForResponse(r=>r.url().includes('/raonslab-travel_lab/catalog?')&&new URL(r.url()).searchParams.get('q')===q&&Number(new URL(r.url()).searchParams.get('page')||1)===pageNo);
 const firstPromise=catalogResponse(1);await go('/travel/search?q='+encodeURIComponent(q)+'&sort=price_asc');const first=await (await firstPromise).json();await catalog();expect(first.data.pagination.total).toBeGreaterThan(12);expect(first.data.data).toHaveLength(12);expect(first.data.data.every(x=>ownIds.includes(x.id))).toBe(true);await expect.poll(()=>page.getByTestId('trip-card').count()).toBe(12);const firstIds=first.data.data.map(x=>x.id);const pager=page.getByRole('navigation',{name:'페이지 이동'});await expect(pager).toBeVisible();await screenshot('pagination-page1');const secondPromise=catalogResponse(2);await pointer(pager.getByRole('button',{name:'다음 페이지',exact:true}));const second=await (await secondPromise).json();await catalog();expect(new URL(page.url()).searchParams.get('page')).toBe('2');expect(new URL(page.url()).searchParams.get('q')).toBe(q);expect(new URL(page.url()).searchParams.get('sort')).toBe('price_asc');expect(second.data.data.length).toBeGreaterThan(0);expect(second.data.data.every(x=>ownIds.includes(x.id)&&!firstIds.includes(x.id))).toBe(true);await expect.poll(()=>page.getByTestId('trip-card').evaluateAll(es=>es.map(e=>e.getAttribute('aria-label')))).toEqual(second.data.data.map(x=>x.title));await overflow('pagination');await screenshot('pagination-page2');await page.reload();await catalog();expect(new URL(page.url()).searchParams.get('page')).toBe('2');await expect.poll(()=>page.getByTestId('trip-card').evaluateAll(es=>es.map(e=>e.getAttribute('aria-label')))).toEqual(second.data.data.map(x=>x.title));return {fixtureRole:'Native admin API created OWN synthetic pagination support only; not adminUIcreate verification',firstIds,secondIds:second.data.data.map(x=>x.id),total:first.data.pagination.total,pointer:width===390?'touch tap':'mouse click',reloadPage2:true};});
 await test('detail-itinerary-departure-people-estimate',async()=>{await pointer(page.getByTestId('trip-card').first());await expect(page.getByTestId('product-title')).toBeVisible();await expect(page.getByTestId('departures-loading')).toHaveCount(0);await expect(page.getByTestId('itinerary')).toContainText('1일차');const departure=page.getByTestId('departure-option').filter({hasNotText:'마감'}).first();await pointer(departure);await expect(page.getByTestId('people-value')).toContainText('1명');await pointer(page.getByTestId('people-increase'));await expect(page.getByTestId('people-value')).toContainText('2명');await pointer(page.getByTestId('people-decrease'));await expect(page.getByTestId('people-value')).toContainText('1명');await expect(page.getByTestId('estimate')).not.toContainText('출발일을 골라');await expect(page.getByTestId('simulation-notice')).toContainText('테스트');await expect(page.getByTestId('login-to-add')).toBeVisible();await overflow('detail');await screenshot('detail');return {path:new URL(page.url()).pathname,departures:await page.getByTestId('departure-option').allTextContents()};});
 await test('soldout-disabled',async()=>{const supplied=(process.env.W04_DETAIL_IDS||'').split(',').filter(Boolean).map(Number);let ids=supplied;if(!ids.length){const r=await context.request.get(base+'/api/modules/raonslab-travel_lab/catalog?per_page=48');const j=await r.json();ids=j.data.data.filter(x=>x.departures.some(d=>d.available===0)).map(x=>x.id);}if(!ids.length)return {status:'NOT_RUN',reason:'No public sold-out departure found; cannot alter authored fixtures. Read-only catalog observation is not sold-out UI PASS.'};const observed=[];
 for(const id of ids){const detailPromise=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/modules/raonslab-travel_lab/catalog/'+id&&r.request().method()==='GET');const depsPromise=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/modules/raonslab-travel_lab/catalog/'+id+'/departures'&&r.request().method()==='GET');await go('/travel/products/'+id);const detailResponse=await detailPromise,depsResponse=await depsPromise;expect(detailResponse.status()).toBe(200);expect(depsResponse.status()).toBe(200);const detail=(await detailResponse.json()).data;const raw=(await depsResponse.json()).data;const deps=Array.isArray(raw)?raw:(raw.data||raw.departures);await page.getByTestId('product-title').waitFor();await expect(page.getByTestId('departures-loading')).toHaveCount(0);const sold=deps.filter(d=>d.available===0);expect(sold.length).toBeGreaterThan(0);const option=page.getByTestId('departure-option').filter({hasText:'마감'}).first();await expect(option).toBeDisabled();expect(detail.from_price).toBe(13000);expect(sold.some(d=>d.unit_price===9000)).toBe(true);await expect(page.getByTestId('product-title')).toContainText(detail.title);await overflow('soldout-detail');await screenshot('soldout-'+id);observed.push({product:id,fromPrice:detail.from_price,soldoutUnitPrices:sold.map(d=>d.unit_price),soldoutDisabled:true,activeAvailability:deps.filter(d=>d.available>0).map(d=>d.available),noCartMutation:true});}return {observed};});
 await test('empty-and-reset-action',async()=>{await go('/travel/search');await catalog();await filters();await page.getByTestId('filter-q').fill('W04_PUBLIC_NO_MATCH_76c856ee');const response=page.waitForResponse(r=>r.url().includes('/catalog?'));await pointer(page.getByTestId('filter-apply'));expect((await response).status()).toBe(200);await expect(page.getByTestId('catalog-empty')).toBeVisible();await screenshot('empty');await pointer(page.getByTestId('catalog-empty').getByRole('button'));await catalog();await overflow('empty-reset');});
 await test('product-not-found-real-404',async()=>{await go('/travel/products/999999999');await expect(page.getByTestId('product-not-found')).toBeVisible();await screenshot('not-found');await overflow('not-found');});
 await test('fault-injection-loading-error-retry-real-success',async()=>{let blocked=0;let release;const gate=new Promise(resolve=>release=resolve);await page.route('**/api/modules/raonslab-travel_lab/catalog?**',async route=>{blocked++;await gate;await route.abort('failed');});await go('/travel/search');await expect(page.getByTestId('catalog-loading')).toBeVisible();await screenshot('loading-fault');release();await expect(page.getByTestId('catalog-error')).toBeVisible({timeout:25000});await screenshot('retry-fault');await page.unroute('**/api/modules/raonslab-travel_lab/catalog?**');const data=await catalogAction(()=>pointer(page.getByTestId('catalog-retry')));await expect(page.getByTestId('catalog-error')).toHaveCount(0);await overflow('retry-recovered');return {faultInjection:'aborted GET catalog after holding response for visible loading; retry then actual HTTP200',blockedRequests:blocked,recoveredCount:data.data.length};});
 await test('native-navigation-mobile-drawer',async()=>{await go('/');await page.getByTestId('region-chip').first().waitFor();if(width===390){await pointer(page.getByTestId('menu-toggle'));await expect(page.getByTestId('mobile-drawer')).toBeVisible();await pointer(page.getByTestId('mobile-drawer').getByText('여행 찾기',{exact:true}));}else await pointer(page.getByTestId('nav-search'));await catalog();expect(new URL(page.url()).pathname).toBe('/travel/search');await overflow('navigation');});
 events.consoleErrorCount=events.consoleErrors.length;events.pageErrorCount=events.pageErrors.length;
 await Promise.all(assetWork);events.assets=[...new Map(assets.map(x=>[x.path,x])).values()];report.viewports.push(events);await context.close();
}
await browser.close();report.finished=new Date().toISOString();report.durationSeconds=(Date.parse(report.finished)-Date.parse(report.started))/1000;report.reuse={source:'attempt1 public-recheck.mjs read-only source reuse; no historical PNG copied',priorOriginalMarkers:{pagination390:'NOT_RUN',pagination1440:'NOT_RUN'}};report.counts=Object.fromEntries(['PASS','FAIL','NOT_RUN','BLOCKED'].map(status=>[status,report.scenarios.filter(x=>x.status===status).length]));
await writeFile(`${dir}/${process.env.W04_ONLY?(process.env.W04_RUN_LABEL||'public-targeted-followup'):'public-results'}.json`,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report.counts));
process.exitCode = report.counts.FAIL ? 1 : 0;
