import fs from 'node:fs';import {syntheticPhone,run as contactRun} from './common.mjs';
import {a,base,out,travel,run,context,login,browser,expect,shot,api,step,owned,cleanup,flush,hash,results,finishTokens,logout} from './common.mjs';
for(const width of [390,1440]){
 const {p,c,m}=await context(width,'member');await login(p,'member');
 const initial=await api(p,travel+'/cart');expect(initial.body.data.items).toHaveLength(0);
 const f=JSON.parse(fs.readFileSync(out+'/admin.json')).owned.products[width===390?0:1];const product={id:f.id};
 for(const mode of ['immediate','reload','edited-contact','localStorage-quota','sessionStorage-quota']){
 await step(width,'recovery '+mode,async()=>{
 await p.goto(base+'/travel/products/'+product.id);await p.getByTestId('departure-option').filter({hasNotText:'마감'}).first().click();const add=p.waitForResponse(r=>r.url().endsWith(travel+'/cart')&&r.request().method()==='POST');await p.getByTestId('add-to-cart').click();const ar=await add;expect(ar.status()).toBe(201);for(const x of (await ar.json()).data.items)owned.carts.push({id:x.id,role:'member'});await p.getByTestId('go-cart').click();
 await p.getByTestId('contact-name').fill(run+' contact '+mode);await p.getByTestId('contact-phone').fill(syntheticPhone());await p.getByTestId('ack-test').check();
 const owner=await p.evaluate(()=>window.G7Core.state.get().currentUser?.uuid);expect(owner).toBeTruthy();
 if(mode.endsWith('-quota'))await p.evaluate(mode=>{window.__quotaOriginal=Storage.prototype.setItem;window.__quotaHits=0;Storage.prototype.setItem=function(k,v){if((mode==='localStorage-quota'&&this===localStorage)||(mode==='sessionStorage-quota'&&this===sessionStorage)){window.__quotaHits++;throw new DOMException('Owned synthetic quota','QuotaExceededError');}return window.__quotaOriginal.call(this,k,v);};},mode);
 let first,retry,created,intercepted=false;
 await p.route('**'+travel+'/inquiries',async r=>{if(r.request().method()!=='POST')return r.continue();if(!intercepted){intercepted=true;first=r.request().postDataJSON();if(mode!=='edited-contact'){const rr=await r.fetch();expect(rr.status()).toBe(201);created=(await rr.json()).data;owned.inquiries.push({id:created.id,role:'member'});flush('recovery');}await r.abort('failed');}else{retry=r.request().postDataJSON();await r.continue();}});
 await p.getByTestId('submit-inquiry').click();await expect.poll(()=>intercepted).toBe(true);await expect(p.getByTestId('submit-inquiry')).toBeEnabled();
 if(mode==='reload'){const empty=await api(p,travel+'/cart');expect(empty.body.data.items).toHaveLength(0);await p.reload();await expect(p.getByTestId('inquiry-recovery-notice')).toBeVisible();await expect(p.getByTestId('contact-name')).toBeDisabled();await p.getByTestId('ack-test').check();}
 if(mode==='edited-contact')await p.getByTestId('contact-phone').fill(syntheticPhone(true));
 const rr=p.waitForResponse(r=>r.url().endsWith(travel+'/inquiries')&&r.request().method()==='POST');await p.getByTestId('submit-inquiry').click();const response=await rr;expect(response.status()).toBe(mode==='edited-contact'?201:200);const d=(await response.json()).data;
 if(mode==='edited-contact'){expect(retry.idempotency_key).not.toBe(first.idempotency_key);expect(retry.contact.phone).not.toBe(first.contact.phone);owned.inquiries.push({id:d.id,role:'member'});}else{expect(retry).toEqual(first);expect(retry.idempotency_key).toBe(first.idempotency_key);expect(d.id).toBe(created.id);}
 await p.unroute('**'+travel+'/inquiries');await expect(p).toHaveURL(new RegExp('/travel/requests/'+d.id));await expect(p.getByTestId('detail-status')).toContainText('테스트 접수');await shot(p,m,'recovery-'+mode);
 let quotaHits;if(mode.endsWith('-quota')){quotaHits=await p.evaluate(()=>{Storage.prototype.setItem=window.__quotaOriginal;return window.__quotaHits;});if(mode==='sessionStorage-quota')expect(quotaHits).toBeGreaterThan(0);}
 await p.getByTestId('cancel-request').click();await expect(p.getByRole('dialog')).toBeVisible();await shot(p,m,'cancel-'+mode);await p.getByTestId('cancel-confirm').click();await expect(p.getByTestId('detail-status')).toContainText('취소');return {...(mode==='localStorage-quota'&&quotaHits===0?{status:'NOT_RUN',reason:'No actual localStorage quota write; response-loss retry passed, fallback not exercised'}:{}),inquiryId:d.id,upstreamCommit:mode!=='edited-contact'?201:'not forwarded',retryStatus:response.status(),fullBodyEqual:mode==='edited-contact'?false:JSON.stringify(first)===JSON.stringify(retry),firstBodySHA256:hash(first),retryBodySHA256:hash(retry),ownerUuidPresent:true,quotaHits};
 },'recovery');await p.unroute('**'+travel+'/inquiries');await p.evaluate(()=>{if(window.__quotaOriginal)Storage.prototype.setItem=window.__quotaOriginal;}).catch(()=>{});
 }
 await step(width,'owner UUID native logout/relogin isolation',async()=>{
 await p.goto(base+'/travel/products/'+product.id);await p.getByTestId('departure-option').filter({hasNotText:'마감'}).first().click();const ar=p.waitForResponse(r=>r.url().endsWith(travel+'/cart')&&r.request().method()==='POST');await p.getByTestId('add-to-cart').click();for(const x of (await (await ar).json()).data.items)owned.carts.push({id:x.id,role:'member'});await p.getByTestId('go-cart').click();await p.getByTestId('contact-name').fill(run+' contact isolation');await p.getByTestId('contact-phone').fill(syntheticPhone());await p.getByTestId('ack-test').check();let key,committed;
 await p.route('**'+travel+'/inquiries',async r=>{if(r.request().method()==='POST'){key=r.request().postDataJSON().idempotency_key;const rr=await r.fetch();expect(rr.status()).toBe(201);committed=(await rr.json()).data.id;owned.inquiries.push({id:committed,role:'member'});await r.abort('failed');}else await r.continue();});await p.getByTestId('submit-inquiry').click();await expect.poll(()=>committed).toBeTruthy();await p.unroute('**'+travel+'/inquiries');const stale=await p.evaluate(()=>({owner:G7Core.state.get().currentUser.uuid,stored:sessionStorage.getItem('raon_travel_inquiry_key')}));if(width===390)await p.getByTestId('menu-toggle').click();const logoutWait=p.waitForResponse(r=>r.url().endsWith('/api/auth/logout'));await p.getByRole('button',{name:'로그아웃',exact:true}).click();expect((await logoutWait).status()).toBe(200);await expect(p).toHaveURL(/\/login/);await login(p,'other_member');await p.goto(base+'/travel/cart');await expect(p.getByTestId('inquiry-recovery-notice')).toHaveCount(0);await expect(p.getByText('아직 담은 여행이 없어요')).toBeVisible();await expect.poll(()=>p.evaluate(()=>!!G7Core.state.get().currentUser?.uuid)).toBe(true);const cleared=await p.evaluate(()=>{const s=G7Core.state.get();return !s.travelInquiryKey&&!s.travelInquiryPending&&!s.travelInquiryContact&&!sessionStorage.getItem('raon_travel_inquiry_key');});expect(cleared).toBe(true);await p.evaluate(async stale=>{sessionStorage.setItem('raon_travel_inquiry_key',stale.stored);await G7Core.dispatch({handler:'travelLabEnsureInquiryKey',params:{ownerId:stale.owner,cartIds:[],quantities:[]}});},stale);expect(await p.evaluate(()=>{const s=G7Core.state.get();return !s.travelInquiryKey&&!s.travelInquiryPending&&!s.travelInquiryContact;})).toBe(true);await shot(p,m,'foreign-relogin-empty');await logout(p,width);await login(p,'member');await p.goto(base+'/travel/requests/'+committed);await expect(p.getByTestId('detail-status')).toContainText('테스트 접수');await p.getByTestId('cancel-request').click();await p.getByTestId('cancel-confirm').click();await expect(p.getByTestId('detail-status')).toContainText('취소');return {ownerKeySHA256:hash(key),inquiryId:committed,foreignRecoveryAbsent:true};
 },'recovery');await c.close();
}
const cp=await browser.newPage();await cleanup(cp);flush('recovery');await finishTokens(await browser.newPage());await browser.close();process.exitCode=results.some(r=>r.status==='FAIL')?1:0;
