// W04 Retry closure 독립 검증 전용 (5783e6ba). 허용된 인계만 프로세스 내부에서 읽고 private 장부는 ignored 0600.
import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {execFileSync} from 'node:child_process';import {chromium,expect as ex,request as pwRequest} from '@playwright/test';
export const expect=ex.configure({timeout:12000});
export const SHA='5783e6ba124061bdfae639cdaf9b1c14a83cdf03',TREE='361f9a142572f8a6c0c28326c461a233a92aec4e',base='http://127.0.0.1:18871',travel='/api/modules/raonslab-travel_lab',pages='/api/modules/sirsoft-page/admin/pages',shop='/api/modules/sirsoft-ecommerce',out='tests/W04_RETRY_BROWSER/evidence',priv='storage/framework/testing/w04-retry-4d7d-private';
const accessPath='/home/ubuntu/.agentopt-v2/workspaces/req_81ac33cac94046b9a2249cd14c0d00ba/storage/framework/testing/travel-campaign-retry-final/access.json';
if(fs.lstatSync(accessPath).isSymbolicLink()||(fs.statSync(accessPath).mode&0o777)!==0o600||(fs.statSync(path.dirname(accessPath)).mode&0o777)!==0o700)throw Error('Scoped handoff permissions rejected');
export const a=JSON.parse(fs.readFileSync(accessPath));
if(a.source_sha!==SHA||a.source_tree!==TREE||a.db!=='req81_travel_lab'||a.base_url!==base||Date.parse(a.expires_at)<Date.now()+300000)throw Error('Scoped source/APP/loopback/expiry rejected');
const current=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim();execFileSync('git',['merge-base','--is-ancestor',SHA,current]);
if(execFileSync('git',['rev-parse',SHA+'^{tree}'],{encoding:'utf8'}).trim()!==TREE)throw Error('Tree mismatch');
const changed=execFileSync('git',['diff','--name-only',SHA,'--','.',':!tests/W04_RETRY_BROWSER',':!docs/symphony/W04_RETRY_BROWSER_CLOSURE.md'],{encoding:'utf8'}).trim();if(changed)throw Error('Product source differs from fixed SHA: '+changed);
fs.mkdirSync(priv,{recursive:true,mode:0o700});if(fs.statSync(priv).mode&0o077)throw Error('Own private directory mode');fs.mkdirSync(out,{recursive:true});
export const hash=x=>crypto.createHash('sha256').update(Buffer.isBuffer(x)||typeof x==='string'?x:JSON.stringify(x)).digest('hex');
export function readPrivate(n,fallback=null){return fs.existsSync(priv+'/'+n+'.json')?JSON.parse(fs.readFileSync(priv+'/'+n+'.json')):fallback;}
export function savePrivate(n,v){fs.writeFileSync(priv+'/'+n+'.json',JSON.stringify(v),{mode:0o600});}
export const ROLES=['member','other_member','admin','readonly','self_reader'];
const issued=readPrivate('issued',[]);
export const secrets=()=>[...ROLES.flatMap(r=>[a[r].email,a[r].password,a[r].bearer_token]),...issued.map(t=>t.token),...readPrivate('actor-names',[]),readPrivate('contact',{}).name].filter(x=>x&&String(x).length>3);
export function scrub(s){s=String(s);for(const x of secrets())s=s.split(x).join('[PRIVATE]');return s.replace(/[\w.+-]+@[\w.-]+\.[\w-]+/g,'[EMAIL]').replace(/[a-f\d]{8}(?:-[a-f\d]{4}){3}-[a-f\d]{12}/gi,'[UUID]').replace(/\d+\|[A-Za-z\d]{20,}/g,'[TOKEN]').replace(/signature=[^\s"&]+/g,'signature=[PRIVATE]');}
export const phase=process.argv[2]??'inspect',output=out+'/'+phase+'.json';if(fs.existsSync(output))throw Error('Append-only phase already exists');
export const result={phase,tested_sha:SHA,tree:TREE,actual_head:current,argv:process.argv.slice(2),started:new Date().toISOString(),checks:[],metrics:[],cleanup:[]};
export function flush(){result.elapsed_seconds=(Date.now()-Date.parse(result.started))/1000;fs.writeFileSync(output,scrub(JSON.stringify(result,null,2))+'\n');}
const STAT=['PASS','FAIL','NOT_RUN','BLOCKED','OBSERVED'];
export async function step(width,name,fn){try{const data=await fn();result.checks.push({width,name,status:STAT.includes(data?.status)?data.status:'PASS',data});console.log(width,name,result.checks.at(-1).status);return data;}catch(e){result.checks.push({width,name,status:'FAIL',error:scrub(e.message).slice(0,1600)});console.log(width,name,'FAIL',scrub(e.message).slice(0,400));return null;}finally{flush();}}
export const browser=await chromium.launch({executablePath:'/home/ubuntu/.cache/ms-playwright/chromium-1248/chrome-linux64/chrome',args:['--disable-background-networking']});result.chromium=browser.version();
const request=await pwRequest.newContext();
export async function api(endpoint,method='GET',data,role='admin',token){const headers={Accept:'application/json','Accept-Language':'ko'};const t=token??(role?await ownToken(role):null);if(t)headers.Authorization='Bearer '+t;const r=await request.fetch(base+endpoint,{method,headers,...(data===undefined?{}:{data})});let body;try{body=await r.json();}catch{body=null;}return {status:r.status(),body};}
// 인계 bearer 는 사전관찰(probe-1, 21:24:42Z)에서 이미 401 — API 작업은 native 로그인으로 직접 발급한 자기 토큰만 사용한다.
async function ownToken(role){let t=issued.filter(x=>x.role===role&&!x.revoked&&x.phase===phase).at(-1);if(t)return t.token;const r=await request.fetch(base+'/api/auth/login',{method:'POST',headers:{Accept:'application/json'},data:{email:a[role].email,password:a[role].password}});if(r.status()!==200)throw Error('Native API login '+role+' '+r.status());const b=await r.json();const token=b.data.token??b.data.access_token;issued.push({role,token,hash:hash(token),at:new Date().toISOString(),phase,via:'api-login'});savePrivate('issued',issued);return token;}
export async function suppliedStatus(){const o={};for(const role of ['admin','member','other_member']){const r=await request.fetch(base+'/api/auth/user',{headers:{Accept:'application/json',Authorization:'Bearer '+a[role].bearer_token}});o[role]=r.status();}return o;}
export async function required(endpoint,method='GET',data,status=200,role='admin'){const r=await api(endpoint,method,data,role);if(r.status!==status)throw Error('Native '+method+' '+endpoint+' expected '+status+' got '+r.status+' errors '+Object.keys(r.body?.errors??{}).join(','));return r.body.data;}
export async function context(width,role='guest'){const c=await browser.newContext({viewport:{width,height:1000},isMobile:width===390,hasTouch:width===390,locale:'ko-KR'});await c.addInitScript(()=>{window.__w04inputs=[];for(const t of ['click','keydown'])document.addEventListener(t,e=>{const n=e.target instanceof Element?e.target.closest('[data-testid],button,a'):null;window.__w04inputs.push({type:e.type,key:e.key??null,trusted:e.isTrusted,tag:n?.tagName,testid:n?.getAttribute('data-testid'),pointerType:e.pointerType??null});},true);});const p=await c.newPage();p.setDefaultTimeout(12000);const wait=p.waitForResponse.bind(p);p.waitForResponse=(...args)=>{const promise=wait(...args);promise.catch(()=>{});return promise;};const m={width,role,pageerrors:[],external_attempts:[],external_connections:[],http:[],assets:[],geometry:[]};result.metrics.push(m);
await c.route('**/*',async r=>{const u=new URL(r.request().url());if(['http:','https:'].includes(u.protocol)&&u.origin!==base){m.external_attempts.push({origin:u.origin,path:u.pathname,resource:r.request().resourceType()});await r.abort('blockedbyclient');}else await r.fallback();});
p.on('pageerror',e=>m.pageerrors.push(scrub(e.message)));p.on('response',r=>{const u=new URL(r.url());if(u.origin!==base)m.external_connections.push({origin:u.origin,status:r.status()});if(u.pathname.startsWith('/api/'))m.http.push({path:u.pathname,method:r.request().method(),status:r.status()});if(/\.(js|css|woff2?)$/.test(u.pathname))r.body().then(b=>{const x={path:u.pathname,sha256:hash(b),status:r.status(),bytes:b.length};if(!m.assets.some(a=>a.path===x.path&&a.sha256===x.sha256))m.assets.push(x);}).catch(()=>{});});return {c,p,m};}
export const act=loc=>loc.page().viewportSize().width===390?loc.tap():loc.click();
export async function login(p,role){await p.goto(base+'/login');await p.locator('#travel-login-email').fill(a[role].email);await p.locator('#travel-login-password').fill(a[role].password);const w=p.waitForResponse(r=>new URL(r.url()).pathname==='/api/auth/login'&&r.request().method()==='POST');await act(p.getByTestId('login-submit'));const r=await w;expect(r.status()).toBe(200);const b=await r.json();const token=b.data.token??b.data.access_token;if(!token)throw Error('Missing native token');issued.push({role,token,hash:hash(token),at:new Date().toISOString(),phase});savePrivate('issued',issued);const profile=await api('/api/auth/user','GET',undefined,null,token);const names=readPrivate('actor-names',[]);if(profile.body?.data?.name&&!names.includes(profile.body.data.name)){names.push(profile.body.data.name);savePrivate('actor-names',names);}await expect(p).not.toHaveURL(/\/login/);return token;}
// 실제 native UI 로그아웃: 390 menu-toggle → 정확한 '로그아웃' / 1440 header-logout. 이후 정확한 옛 토큰 /api/auth/user 401.
export async function uiLogout(p,token){const w=p.waitForResponse(r=>new URL(r.url()).pathname==='/api/auth/logout'&&r.request().method()==='POST');if(p.viewportSize().width===390){await act(p.getByTestId('menu-toggle'));const b=p.getByRole('button',{name:'로그아웃',exact:true}).filter({visible:true});await expect(b).toHaveCount(1);await act(b);}else await act(p.getByTestId('header-logout'));const r=await w;const sent=(r.request().headers()['authorization']??'').replace(/^Bearer /,'');const q=await api('/api/auth/user','GET',undefined,null,token);const t=issued.find(x=>x.token===token);if(t&&q.status===401){t.revoked='ui';savePrivate('issued',issued);}return {logout:r.status(),sentExactOwnToken:sent===token,oldTokenUser:q.status,token_hash:hash(token),status:r.status()===200&&q.status===401&&sent===token?'PASS':'FAIL'};}
export async function revoke(){for(const t of issued.filter(x=>x.phase===phase)){if(t.revoked){const q=await api('/api/auth/user','GET',undefined,null,t.token);result.cleanup.push({type:'exact-own-token',role:t.role,hash:t.hash,via:t.revoked,requery:q.status,status:q.status===401?'PASS':'FAIL'});continue;}const r=await api('/api/auth/logout','POST',{},null,t.token);const q=await api('/api/auth/user','GET',undefined,null,t.token);if(q.status===401){t.revoked='api';}result.cleanup.push({type:'exact-own-token',role:t.role,hash:t.hash,via:'api',logout:r.status,requery:q.status,status:r.status===200&&q.status===401?'PASS':'FAIL'});}savePrivate('issued',issued);const sup=await suppliedStatus();for(const role of Object.keys(sup))result.cleanup.push({type:'supplied-handoff-observed',role,http:sup[role],status:'OBSERVED',note:'supplied bearer already 401 at first preflight probe-1 before any write; never used for logout/revocation by this verifier'});flush();}
export async function shot(p,m,name,{crop}={}){await p.waitForTimeout(600);await p.evaluate(values=>{window.__maskOrig=[...document.querySelectorAll('input,textarea,[contenteditable=true]')].map(e=>[e,e.style.cssText]);for(const [e] of __maskOrig)e.style.setProperty('visibility','hidden','important');const w=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let n;while(n=w.nextNode()){if(n.parentElement?.closest('script,style'))continue;let s=n.textContent;for(const v of values)s=s.split(v).join('[MASKED]');n.textContent=s.replace(/[\w.+-]+@[\w.-]+\.[\w-]+/g,'[MASKED EMAIL]').replace(/[a-f\d]{8}(?:-[a-f\d]{4}){3}-[a-f\d]{12}/gi,'[MASKED UUID]');}},secrets());m.inputs??=[];m.inputs.push({path:new URL(p.url()).pathname,events:await p.evaluate(()=>window.__w04inputs??[])});const file=out+'/'+name+'-'+m.width+'.png';if(fs.existsSync(file))throw Error('Screenshot phase already exists');if(crop)await p.locator(crop).screenshot({path:file});else await p.screenshot({path:file,fullPage:true});const ocr=execFileSync('tesseract',[file,'stdout','-l','eng'],{encoding:'utf8',stdio:['ignore','pipe','ignore'],env:{...process.env,OMP_THREAD_LIMIT:'1'},timeout:60000});if(secrets().some(v=>v.length>5&&ocr.includes(v))||/[\w.+-]+@[\w-]+\.[\w-]+/.test(ocr)){fs.renameSync(file,priv+'/quarantine-'+path.basename(file));throw Error('Screenshot privacy rejected');}await p.evaluate(()=>{for(const [e,s]of __maskOrig)e.style.cssText=s;});const g=await p.evaluate(()=>({viewport:innerWidth,document:document.documentElement.scrollWidth}));m.geometry.push({name,...g});result.checks.push({name:'masked screenshot '+name,width:m.width,status:'PASS',known_private_ocr_hits:0,path:file,sha256:hash(fs.readFileSync(file)),geometry:g});flush();}
export async function finish(){await revoke();await request.dispose();await browser.close();result.finished=new Date().toISOString();flush();process.exitCode=result.checks.some(x=>x.status==='FAIL')||result.cleanup.some(x=>x.status==='FAIL')?1:0;}
