// 인가된 단일 창: 부모 합성 nature 상품 1/3 의 travel published 만 false → 실제 게스트 캠페인 본문200 + 실제 빈 카탈로그 → 원래 boolean/의미 상태로 복원.
// 가격/재고/정원/옵션/출발일 변경 없음. 성공 응답 mock 없음. 알 수 없는 nature ID 발견 시 BLOCKED 로 중단.
import {base,travel,shop,context,act,api,step,shot,result,hash,readPrivate,savePrivate,finish,expect,flush} from './common.mjs';
const SLUG='travel-lab-campaign-autumn-escape',IDS=[1,3];
const strip=o=>Array.isArray(o)?o.map(strip):o&&typeof o==='object'?Object.fromEntries(Object.entries(o).filter(([k])=>!['updated_at','updated_at_formatted'].includes(k)).map(([k,v])=>[k,strip(v)])):o;
async function publicIds(theme){const ids=[];let page=1,last=1,pages=0;do{const r=await api(travel+'/catalog?per_page=48&page='+page+(theme?'&theme='+theme:''),'GET',undefined,null);if(r.status!==200)throw Error('catalog '+r.status);ids.push(...r.body.data.data.map(x=>x.id));last=r.body.data.meta?.last_page??1;page++;pages++;}while(page<=last);return {ids:ids.sort((a,b)=>a-b),pages};}
async function snap(){const o={};for(const id of IDS){const t=await api(travel+'/admin/catalog/'+id,'GET',undefined,'admin');const d=await api(travel+'/admin/catalog/'+id+'/departures','GET',undefined,'admin');const s=await api(shop+'/admin/products/'+id,'GET',undefined,'admin');if([t,d,s].some(x=>x.status!==200))throw Error('snapshot '+id+' '+[t.status,d.status,s.status]);o[id]={travel:t.body.data,departures:d.body.data,product:s.body.data};}return o;}
function facets(o){const r={};for(const id of IDS){const x=o[id];r[id]={published:x.travel.published,theme:x.travel.theme,semantic:hash(strip(x)),departures:hash(strip(x.departures).map(d=>({id:d.id,date:d.departure_date,ret:d.return_date,capacity:d.capacity,reserved:d.reserved,active:d.is_active,option:d.product_option_id}))),price:hash([x.product.list_price,x.product.selling_price]),options:hash(strip(x.product.options)),stock:hash([x.product.stock_quantity,(x.product.options??[]).map(p=>p.stock_quantity)]),reserved:(x.departures??[]).map(d=>d.reserved)};}return r;}
let mutated=false;
try{
  const pre=await step(null,'preflight: exhaust per_page48 pagination, nature IDs exactly 1/3, private native admin snapshots',async()=>{const nature=await publicIds('nature');const all=await publicIds(null);const big=(await api(travel+'/catalog?per_page=100','GET',undefined,null)).status;if(JSON.stringify(nature.ids)!==JSON.stringify(IDS))return {status:'BLOCKED',nature,reason:'unexpected nature product set — scenario stopped, nothing hidden'};const s=await snap();for(const id of IDS){if(s[id].travel.theme!=='nature'||s[id].travel.published!==true)return {status:'BLOCKED',reason:'snapshot theme/published unexpected for '+id};}savePrivate('empty-original',s);return {nature,allPublic:all,perPage100:big,facets:facets(s),private_snapshot_sha256:hash(s)};});
  if(pre&&pre.status!=='BLOCKED'){
    await step(null,'PATCH only published=false for 1/3 (native admin)',async()=>{const o={};for(const id of IDS){mutated=true;const r=await api(travel+'/admin/catalog/'+id,'PATCH',{published:false},'admin');o[id]={http:r.status,published:r.body?.data?.published};expect(r.status).toBe(200);}const nature=await publicIds('nature');expect(nature.ids).toEqual([]);const camp=await api(travel+'/campaigns/'+SLUG,'GET',undefined,null);expect(camp.status).toBe(200);return {patch:o,natureNow:nature,page7PublicCampaign:camp.status,catalogQuery:camp.body?.data?.data?.catalog_query??camp.body?.data?.catalog_query};});
    for(const width of [390,1440])await step(width,'actual guest campaign Page body200, catalog200 data.data[] → campaign_trips-empty + all-trips CTA',async()=>{const {c,p,m}=await context(width,'guest');try{const cw=p.waitForResponse(r=>new URL(r.url()).pathname===travel+'/campaigns/'+SLUG);const tw=p.waitForResponse(r=>{const u=new URL(r.url());return u.pathname===travel+'/catalog'&&u.searchParams.get('theme')==='nature';});await p.goto(base+'/travel/campaigns/'+SLUG);const cr=await cw,tr=await tw;expect(cr.status()).toBe(200);expect(tr.status()).toBe(200);const tb=await tr.json();expect(tb.data.data).toEqual([]);await expect(p.getByTestId('campaign-body')).toBeVisible();await expect(p.getByTestId('campaign_trips-empty')).toBeVisible();expect(await p.getByTestId('campaign_trips-error').count()).toBe(0);expect(await p.locator('[data-testid="campaign_trips-results"] [data-testid="trip-card"]').count()).toBe(0);const bodyLen=(await p.getByTestId('campaign-body').innerText()).length;await shot(p,m,'empty-campaign-catalog');const cta=p.getByTestId('campaign_trips-empty').getByRole('button');await expect(cta).toBeVisible();await act(cta);await expect(p).toHaveURL(/\/travel\/search/);return {campaignHttp:200,catalogHttp:200,catalogRows:0,bodyTextLength:bodyLen,emptyVisible:true,ctaNavigated:'/travel/search',pointer:width===390?'tap':'click'};}finally{await c.close();}});
  }
}finally{
  if(mutated)await step(null,'restore original published booleans and verify exact semantic catalog/departure/price/option/stock state',async()=>{const o=readPrivate('empty-original');const r={};for(const id of IDS){const x=await api(travel+'/admin/catalog/'+id,'PATCH',{published:o[id].travel.published},'admin');r[id]=x.status;}const now=await snap();const a=facets(o),b=facets(now);const nature=await publicIds('nature');const all=await publicIds(null);const same=JSON.stringify(a)===JSON.stringify(b);const upd=IDS.map(id=>({id,before:o[id].travel.updated_at??null,after:now[id].travel.updated_at??null}));result.cleanup.push({type:'parent-synthetic-nature-1-3-restored',status:same&&JSON.stringify(nature.ids)===JSON.stringify(IDS)?'PASS':'FAIL',patch:r,semanticEqual:same,natureIds:nature.ids,allPublic:all.ids});flush();return {status:same?'PASS':'FAIL',restorePatch:r,before:a,after:b,natureIds:nature.ids,allPublicIds:all.ids,updated_at:upd,note:'updated_at excluded from semantic comparison; may legitimately increase'};});
  await finish();}
