// 최종 native readback: Page7/8 원본, nature 1/3, 자기 픽스처 종료 상태, 전체 자기 발급 토큰 401, 인계 토큰 관찰. 쓰기 없음(감사용 자기 토큰은 종료 시 logout).
import {pages,travel,shop,api,step,result,hash,readPrivate,finish,suppliedStatus,expect} from './common.mjs';
const strip=o=>Array.isArray(o)?o.map(strip):o&&typeof o==='object'?Object.fromEntries(Object.entries(o).filter(([k])=>!['updated_at','updated_at_formatted'].includes(k)).map(([k,v])=>[k,strip(v)])):o;
try{
await step(null,'Pages7/8 ID/slug/title/content/mode/publication equal private original',async()=>{const o=readPrivate('pages78-original');const r={};for(const id of [7,8]){const n=(await api(pages+'/'+id,'GET',undefined,'admin')).body.data;const f=x=>({id:x.id,slug:x.slug,title:x.title,content:x.content,content_mode:x.content_mode,published:x.published,seo:x.seo_meta??null});r[id]={fieldsEqual:hash(f(n))===hash(f(o[id])),wholeEqual:hash(n)===hash(o[id]),version:n.current_version,origVersion:o[id].current_version};}return {pages:r,status:Object.values(r).every(x=>x.fieldsEqual)?'PASS':'FAIL'};});
await step(null,'parent synthetic nature 1/3 semantic state equals pre-window snapshot; public nature set {1,3}',async()=>{const o=readPrivate('empty-original');const r={};for(const id of [1,3]){const t=(await api(travel+'/admin/catalog/'+id,'GET',undefined,'admin')).body.data;const d=(await api(travel+'/admin/catalog/'+id+'/departures','GET',undefined,'admin')).body.data;const s=(await api(shop+'/admin/products/'+id,'GET',undefined,'admin')).body.data;r[id]=hash(strip({travel:t,departures:d,product:s}))===hash(strip(o[id]));}const n=await api(travel+'/catalog?theme=nature&per_page=48','GET',undefined,null);const ids=n.body.data.data.map(x=>x.id).sort((a,b)=>a-b);return {semanticEqual:r,natureIds:ids,status:Object.values(r).every(Boolean)&&JSON.stringify(ids)==='[1,3]'?'PASS':'FAIL'};});
await step(null,'own fixtures terminal state readback',async()=>{const t=readPrivate('transactions',{products:[],inquiries:[],policies:[]});const out={inquiries:[],products:[],policies:[],support:[],drafts:[]};for(const q of t.inquiries){const d=(await api(travel+'/admin/inquiries/'+q.id,'GET',undefined,'admin')).body.data;out.inquiries.push({id:q.id,status:d.status});}for(const f of t.products){const d=(await api(travel+'/admin/catalog/'+f.id,'GET',undefined,'admin')).body.data;out.products.push({id:f.id,published:d.published,public:(await api(travel+'/catalog/'+f.id,'GET',undefined,null)).status,departures:d.departures.map(x=>({id:x.id,active:x.is_active,reserved:x.reserved}))});}for(const p of t.policies){const d=(await api(shop+'/admin/shipping-policies/'+p.id,'GET',undefined,'admin')).body.data;out.policies.push({id:p.id,active:d.is_active,default:d.is_default});}for(const s of readPrivate('support',[])){out.support.push({id:s.id,channel:s.channel,public:(await api(travel+'/support/'+s.channel+'/'+s.id,'GET',undefined,s.channel==='questions'?'member':null)).status});}for(const d of readPrivate('scope-own',{pages:[]}).pages)out.drafts.push({id:d.id,admin:(await api(pages+'/'+d.id,'GET',undefined,'admin')).status});out.carts={member:(await api(travel+'/cart','GET',undefined,'member')).body.data.items.length,other_member:(await api(travel+'/cart','GET',undefined,'other_member')).body.data.items.length};
  const ok=out.inquiries.every(x=>['CANCELLED','DECLINED'].includes(x.status))&&out.products.every(x=>x.published===false&&x.public===404&&x.departures.every(d=>!d.active&&d.reserved===0))&&out.policies.every(x=>!x.active&&!x.default)&&out.support.every(x=>x.public===404)&&out.drafts.every(x=>x.admin===404)&&out.carts.member===0&&out.carts.other_member===0;return {...out,status:ok?'PASS':'FAIL'};});
await step(null,'every own issued token from earlier phases exact /api/auth/user 401',async()=>{const all=readPrivate('issued',[]).filter(x=>x.phase!==result.phase);const rows=[];for(const t of all){const q=await api('/api/auth/user','GET',undefined,null,t.token);rows.push({phase:t.phase,role:t.role,hash:t.hash,via:t.revoked??null,http:q.status});}return {count:rows.length,byRole:rows.reduce((a,x)=>(a[x.role]=(a[x.role]??0)+1,a),{}),non401:rows.filter(x=>x.http!==401),rows,status:rows.every(x=>x.http===401)?'PASS':'FAIL'};});
await step(null,'supplied handoff bearer status (GET only)',async()=>({supplied:await suppliedStatus(),status:'OBSERVED',note:'all three were 401 at first preflight probe-1 21:24:42Z before any verifier write'}));
}finally{await finish();}
