// 실제 390 tap / 1440 pointer: native Page 목록 GET 만 abort → 오류 → abort 제거 → native200 대기 설치 후 Retry → reload 없이 복구.
// 반복: Retry 자체 실패(abort) → 정직한 오류 유지 → 실제 응답을 잠시 보류(pending, 값 변조 없음) → native200 복구. 성공 응답 mock 없음.
import {base,pages,context,login,act,api,step,shot,result,hash,savePrivate,readPrivate,finish,expect,uiLogout} from './common.mjs';
const isList=u=>{const x=new URL(u);return x.pathname===pages;};
async function baselineAdmin(){const r=await api(pages+'?per_page=100&filters[0][field]=slug&filters[0][operator]=starts_with&filters[0][value]=travel-lab-campaign-','GET',undefined,'admin');expect(r.status).toBe(200);return {list:r.body.data.abilities,rows:r.body.data.data.map(x=>({id:x.id,slug:x.slug,published:x.published,abilities:x.abilities}))};}
async function dom(p){return p.evaluate(()=>{const c=t=>document.querySelectorAll(`[data-testid="${t}"]`).length;const vis=t=>[...document.querySelectorAll(`[data-testid="${t}"]`)].filter(e=>e.offsetParent!==null).length;return {error:vis('campaign-pages-error'),loading:vis('campaign-pages-loading'),titles:vis('campaign-slot-title'),titleText:[...document.querySelectorAll('[data-testid="campaign-slot-title"]')].map(e=>e.textContent.trim()),edit:c('campaign-slot-edit'),detail:c('campaign-slot-detail'),publish:c('campaign-slot-publish'),unpublish:c('campaign-slot-unpublish'),create:c('campaign-slot-create'),missing:c('campaign-slot-missing'),noUpdate:c('campaign-slot-no-update'),marker:window.__w04NoReload??null,navEntries:performance.getEntriesByType('navigation').length,timeOrigin:performance.timeOrigin};});}
async function open(p,m,abortCount){let aborted=0;const handler=async r=>{if(r.request().method()==='GET'&&aborted<abortCount){aborted++;m.aborted=(m.aborted??0)+1;await r.abort('failed');}else await r.fallback();};await p.route(isList,handler);await p.goto(base+'/admin/travel-lab/campaigns');await expect(p.getByTestId('campaign-pages-error')).toBeVisible();await p.evaluate(()=>{window.__w04NoReload='set-'+Math.random();});return {handler,aborted:()=>aborted};}
try{
  const pre=await baselineAdmin();const pages78=readPrivate('pages78-original');if(!pages78){const snap={};for(const id of [7,8]){const r=await api(pages+'/'+id,'GET',undefined,'admin');expect(r.status).toBe(200);snap[id]=r.body.data;}savePrivate('pages78-original',snap);}
  result.baseline={abilities:pre,pages78_private_snapshot_digest:hash(readPrivate('pages78-original'))};
  const widths=process.argv[3]?[Number(process.argv[3])]:[390,1440];const only=process.argv[4];
  for(const width of widths){const {c,p,m}=await context(width,'admin');const token=await login(p,'admin');
    await step(width,'A strict: aborted list GET → error → abort removed → wait native200 installed → Retry → settled recovery, no reload',async()=>{const o=await open(p,m,1);const errorBefore=await dom(p);await shot(p,m,'retry-A-error');await p.unroute(isList,o.handler);
      const wait=p.waitForResponse(r=>isList(r.url())&&r.request().method()==='GET');const pendingProbe=p.waitForRequest(r=>isList(r.url())&&r.method()==='GET').then(async()=>dom(p));
      await act(p.getByTestId('campaign-pages-retry'));const res=await wait;const pending=await pendingProbe;expect(res.status()).toBe(200);const body=await res.json();
      await expect(p.getByTestId('campaign-pages-error')).toBeHidden();await expect(p.getByTestId('campaign-slot-title')).toHaveCount(2);const after=await dom(p);
      expect(after.marker).toBe(errorBefore.marker);expect(after.timeOrigin).toBe(errorBefore.timeOrigin);expect(after.edit).toBe(2);expect(after.create).toBe(0);
      const respAbilities={list:body.data.abilities,rows:body.data.data.map(x=>({id:x.id,slug:x.slug,published:x.published,abilities:x.abilities}))};expect(respAbilities).toEqual(pre);
      await shot(p,m,'retry-A-recovered');return {aborted:o.aborted(),errorBefore,pendingAtRequestStart:pending,retryHttp:res.status(),after,abilitiesUnchangedVsAdminAPI:true,reload:false,pointer:width===390?'tap':'click'};});
    if(only!=='A')await step(width,'B repeat: Retry itself fails (native requery aborted) → honest error kept, 0 titles → held real request pending → native200 recovery',async()=>{const o=await open(p,m,2);const first=await dom(p);
      const failed=p.waitForEvent('requestfailed',r=>isList(r.url())&&r.method()==='GET');await act(p.getByTestId('campaign-pages-retry'));await failed;await p.waitForTimeout(1200);const afterFail=await dom(p);expect(afterFail.error).toBe(1);expect(afterFail.titles).toBe(0);expect(o.aborted()).toBe(2);await shot(p,m,'retry-B-failed-again');await p.unroute(isList,o.handler);
      let release;const gate=new Promise(r=>release=r);let held=0;const hold=async r=>{if(r.request().method()==='GET'){held++;await gate;await r.continue();}else await r.fallback();};await p.route(isList,hold);
      const wait=p.waitForResponse(r=>isList(r.url())&&r.request().method()==='GET');await act(p.getByTestId('campaign-pages-retry'));await expect.poll(()=>held).toBe(1);await p.waitForTimeout(800);const pending=await dom(p);expect(pending.error).toBe(1);expect(pending.titles).toBe(0);
      release();const res=await wait;expect(res.status()).toBe(200);await expect(p.getByTestId('campaign-pages-error')).toBeHidden();await expect(p.getByTestId('campaign-slot-title')).toHaveCount(2);await p.unroute(isList,hold);const after=await dom(p);expect(after.marker).toBe(first.marker);expect(after.edit).toBe(2);
      const body=await res.json();expect({list:body.data.abilities,rows:body.data.data.map(x=>({id:x.id,slug:x.slug,published:x.published,abilities:x.abilities}))}).toEqual(pre);await shot(p,m,'retry-B-recovered');
      return {aborts:o.aborted(),first,afterFailedRetry:afterFail,pendingHeldRealRequest:pending,recoveredHttp:res.status(),after,noSuccessMock:true,reload:false};});
    await step(width,'own issued token actual UI logout then exact old token 401',async()=>{await p.goto(base+'/');return uiLogout(p,token);});
    await c.close();}
  await step(null,'Pages7/8 unchanged by Retry phase (native admin readback digest)',async()=>{const o=readPrivate('pages78-original');const now={};for(const id of [7,8])now[id]=(await api(pages+'/'+id,'GET',undefined,'admin')).body.data;return {equal:hash(o)===hash(now),status:hash(o)===hash(now)?'PASS':'FAIL'};});
}finally{await finish();}
