// readonly57(unrestricted read) / self58(self read) 실제 UI + native API 범위. 권한·역할 변경 없음. 자기 draft Page 1건만 admin native 로 만들고 삭제.
import {base,pages,travel,context,login,act,api,step,shot,result,hash,readPrivate,savePrivate,finish,expect,uiLogout} from './common.mjs';
const isList=u=>new URL(u).pathname===pages;const CAMP='/admin/travel-lab/campaigns';
async function dom(p){return p.evaluate(()=>{const c=t=>[...document.querySelectorAll(`[data-testid="${t}"]`)].filter(e=>e.offsetParent!==null).length;return {error:c('campaign-pages-error'),titles:c('campaign-slot-title'),titleText:[...document.querySelectorAll('[data-testid="campaign-slot-title"]')].map(e=>e.textContent.trim()),edit:c('campaign-slot-edit'),detail:c('campaign-slot-detail'),publish:c('campaign-slot-publish'),unpublish:c('campaign-slot-unpublish'),create:c('campaign-slot-create'),missing:c('campaign-slot-missing'),hint:c('campaign-slot-create-hint'),noUpdate:c('campaign-slot-no-update')};});}
const pageState=async()=>{const o={};const l=await api(pages+'?per_page=100','GET',undefined,'admin');o.total=l.body.data.meta.total;o.ids=l.body.data.data.map(x=>x.id).sort((a,b)=>a-b);for(const id of [7,8]){const r=await api(pages+'/'+id,'GET',undefined,'admin');o[id]=hash(r.body.data);}return o;};
try{
  const orig=readPrivate('pages78-original');const v7=(await api(pages+'/7/versions','GET',undefined,'admin')).body?.data;const anyVersion=(Array.isArray(v7)?v7:v7?.data??[])[0]?.id;
  const before=await pageState();result.before={total:before.total,ids:before.ids};
  for(const width of [390,1440]){
    // readonly57
    {const {c,p,m}=await context(width,'readonly');const token=await login(p,'readonly');
      await step(width,'readonly57 campaign adapter: 2 slot titles, abilities false, no create/edit/publish controls',async()=>{const w=p.waitForResponse(r=>isList(r.url())&&r.request().method()==='GET');await p.goto(base+CAMP);const r=await w;expect(r.status()).toBe(200);const b=await r.json();await expect(p.getByTestId('campaign-slot-title')).toHaveCount(2);const d=await dom(p);expect(d).toMatchObject({error:0,titles:2,edit:0,publish:0,unpublish:0,create:0,missing:0,noUpdate:2,detail:2});const abil={list:b.data.abilities,rows:b.data.data.filter(x=>[7,8].includes(x.id)).map(x=>({id:x.id,...x.abilities}))};expect(abil.list).toEqual({can_create:false,can_update:false,can_delete:false});for(const x of abil.rows)expect([x.can_create,x.can_update,x.can_delete]).toEqual([false,false,false]);await shot(p,m,'readonly-campaigns');return {http:200,dom:d,abilities:abil};});
      await step(width,'readonly57 actual detail navigation Page7 and Page8 detail: write controls not enabled',async()=>{const out=[];for(const [slot,id] of [['campaign-slot-autumn-escape',7],['campaign-slot-weekend-reset',8]]){await p.goto(base+CAMP);await expect(p.getByTestId('campaign-slot-title')).toHaveCount(2);const dw=p.waitForResponse(r=>new URL(r.url()).pathname===pages+'/'+id&&r.request().method()==='GET');await act(p.getByTestId(slot).getByTestId('campaign-slot-detail'));await expect(p).toHaveURL(new RegExp('/admin/pages/'+id+'$'));const dr=await dw;expect(dr.status()).toBe(200);const title=(await dr.json()).data.title?.ko??'';await expect(p.getByText(title,{exact:false}).first()).toBeVisible();await p.waitForTimeout(500);const enabledWrite=await p.evaluate(()=>[...document.querySelectorAll('button')].filter(b=>b.offsetParent!==null&&!b.disabled&&/수정|삭제|복원|발행|공개 전환|비공개/.test(b.textContent)).map(b=>b.textContent.trim().slice(0,20)));expect(enabledWrite).toEqual([]);if(id===7)await shot(p,m,'readonly-page7-detail');out.push({id,detail:200,titleVisible:true,enabledWriteButtons:enabledWrite.length});}const vr=await api(pages+'/7/versions','GET',undefined,'readonly');return {pages:out,versionsHttp:vr.status};});
      await step(width,'readonly57 own token actual UI logout then exact old token 401',async()=>{await p.goto(base+'/');return uiLogout(p,token);});await c.close();}
    // self58
    {const {c,p,m}=await context(width,'self_reader');const token=await login(p,'self_reader');
      await step(width,'self58 campaign adapter: native200 scoped empty list, missing hints, no create',async()=>{const w=p.waitForResponse(r=>isList(r.url())&&r.request().method()==='GET');await p.goto(base+CAMP);const r=await w;expect(r.status()).toBe(200);const b=await r.json();expect(b.data.data.length).toBe(0);await expect(p.getByTestId('campaign-slot-missing')).toHaveCount(2);const d=await dom(p);expect(d).toMatchObject({error:0,titles:0,create:0,missing:2,hint:2,edit:0,publish:0,unpublish:0});expect(b.data.abilities).toEqual({can_create:false,can_update:false,can_delete:false});await shot(p,m,'self-reader-campaigns');return {http:200,rows:0,total:b.data.meta?.total,dom:d,abilities:b.data.abilities};});
      await step(width,'self58 actual browser direct foreign Page7 detail URL: native403 (not 404)',async()=>{const w=p.waitForResponse(r=>new URL(r.url()).pathname===pages+'/7'&&r.request().method()==='GET');await p.goto(base+'/admin/pages/7');const r=await w;expect(r.status()).toBe(403);await p.waitForTimeout(800);const leaked=await p.getByText(orig[7].title?.ko??'@@none',{exact:false}).count();expect(leaked).toBe(0);await shot(p,m,'self-reader-foreign-detail');return {http:403,titleLeaked:false,url:'/admin/pages/7'};});
      await step(width,'self58 own token actual UI logout then exact old token 401',async()=>{await p.goto(base+'/');return uiLogout(p,token);});await c.close();}
  }
  await step(null,'native API scope matrix: self403 foreign detail/versions, readonly200, guest401, member403, own customer draft404',async()=>{const o={};for(const id of [7,8]){o['self_show_'+id]=(await api(pages+'/'+id,'GET',undefined,'self_reader')).status;o['self_versions_'+id]=(await api(pages+'/'+id+'/versions','GET',undefined,'self_reader')).status;o['readonly_show_'+id]=(await api(pages+'/'+id,'GET',undefined,'readonly')).status;o['readonly_versions_'+id]=(await api(pages+'/'+id+'/versions','GET',undefined,'readonly')).status;}if(anyVersion){o.self_version_item=(await api(pages+'/7/versions/'+anyVersion,'GET',undefined,'self_reader')).status;o.readonly_version_item=(await api(pages+'/7/versions/'+anyVersion,'GET',undefined,'readonly')).status;}
    o.guest_list=(await api(pages,'GET',undefined,null)).status;o.member_list=(await api(pages,'GET',undefined,'member')).status;o.member_show_7=(await api(pages+'/7','GET',undefined,'member')).status;
    const own=readPrivate('scope-own',{pages:[]});const slug='w04-4d7d-draft-'+Date.now();const cr=await api(pages,'POST',{slug,title:{ko:'W04 4d7d 합성 비공개 초안',en:'W04 4d7d synthetic draft'},content:{ko:'합성 초안',en:'synthetic draft'},content_mode:'text',published:false},'admin');expect(cr.status).toBe(201);own.pages.push({id:cr.body.data.id,slug});savePrivate('scope-own',own);
    o.customer_draft_public=(await api('/api/modules/sirsoft-page/pages/'+slug,'GET',undefined,'member')).status;o.guest_draft_public=(await api('/api/modules/sirsoft-page/pages/'+slug,'GET',undefined,null)).status;o.self_own_draft=(await api(pages+'/'+cr.body.data.id,'GET',undefined,'self_reader')).status;
    o.travel_campaign_unknown=(await api(travel+'/campaigns/'+slug,'GET',undefined,null)).status;
    const exp={self_show_7:403,self_show_8:403,self_versions_7:403,self_versions_8:403,readonly_show_7:200,readonly_show_8:200,readonly_versions_7:200,readonly_versions_8:200,guest_list:401,member_list:403,member_show_7:403,customer_draft_public:404,guest_draft_public:404,self_own_draft:403,travel_campaign_unknown:404};if(anyVersion){exp.self_version_item=403;exp.readonly_version_item=200;}expect(o).toEqual(exp);return {observed:o,ownDraftFixture:cr.body.data.id};});
  await step(null,'scoped actors valid writes all 403 and no rows changed',async()=>{const o={};const o7=orig[7];const upd={slug:o7.slug,title:o7.title,content:o7.content,content_mode:o7.content_mode,published:o7.published};for(const role of ['readonly','self_reader']){o[role]={create:(await api(pages,'POST',{slug:'w04-4d7d-denied-'+role,title:{ko:'거부 확인',en:'denied'},content:{ko:'x',en:'x'},content_mode:'text',published:false},role)).status,update:(await api(pages+'/7','PUT',upd,role)).status,publish:(await api(pages+'/7/publish','PATCH',{published:false},role)).status,bulk:(await api(pages+'/bulk-publish','PATCH',{ids:[7,8],published:false},role)).status,delete:(await api(pages+'/8','DELETE',undefined,role)).status,checkSlug:(await api(pages+'/check-slug','POST',{slug:'w04-4d7d-x'},role)).status};if(anyVersion)o[role].restore=(await api(pages+'/7/versions/'+anyVersion+'/restore','POST',{},role)).status;}
    const after=await pageState();const own=readPrivate('scope-own').pages.map(x=>x.id);const expectIds=[...before.ids,...own].sort((a,b)=>a-b);const unchanged=after[7]===before[7]&&after[8]===before[8]&&JSON.stringify(after.ids)===JSON.stringify(expectIds);
    const writes=Object.values(o).flatMap(x=>Object.entries(x).filter(([k])=>k!=='checkSlug').map(([,v])=>v));return {observed:o,pages78DigestUnchanged:after[7]===before[7]&&after[8]===before[8],idsOnlyPlusOwnDraft:JSON.stringify(after.ids)===JSON.stringify(expectIds),status:writes.every(s=>s===403)&&unchanged?'PASS':'FAIL'};});
}finally{
  for(const f of readPrivate('scope-own',{pages:[]}).pages){if(f.deleted)continue;const d=await api(pages+'/'+f.id,'DELETE',undefined,'admin');const q=await api(pages+'/'+f.id,'GET',undefined,'admin');const pub=await api('/api/modules/sirsoft-page/pages/'+f.slug,'GET',undefined,null);result.cleanup.push({type:'own-draft-page-deleted',id:f.id,delete:d.status,adminRead:q.status,public:pub.status,status:d.status===200&&q.status===404&&pub.status===404?'PASS':'FAIL'});if(q.status===404){const own=readPrivate('scope-own');own.pages.find(x=>x.id===f.id).deleted=true;savePrivate('scope-own',own);}}
  await finish();}
